import type { Category } from "./types";

// 15 categories — locked ordering preserved exactly. prerequisiteCategoryIds are
// ADVISORY only (used for recommendations/readiness), never to block navigation.
export const categories: Category[] = [
  {
    id: "category-python-foundations",
    order: 1,
    title: "Python Foundations for AI Engineering",
    slug: "python-foundations",
    description: "The minimum Python needed to build the AI systems in this roadmap — no more.",
    purpose: "Reach practical Python fluency for AI glue code without becoming an advanced Python developer first.",
    track: "core",
    estimatedHours: 43,
    difficulty: { from: "beginner", to: "intermediate" },
    topicIds: [
      "topic-py-core-syntax",
      "topic-py-data-structures",
      "topic-py-functions-modules",
      "topic-py-env-tooling",
      "topic-py-async-http",
      "topic-py-errors-logging",
      "topic-py-data-libs",
      "topic-py-optional-depth",
    ],
    projectIds: [],
    prerequisiteCategoryIds: [],
    learningGoals: [
      "Read and write idiomatic Python for AI glue code",
      "Handle JSON/nested data and call REST APIs",
      "Manage environments, dependencies and secrets safely",
      "Use Git and basic CI/CD",
    ],
    whyItMatters: "Every AI system in this roadmap is assembled in Python; you need fluency, not language mastery.",
  },
  {
    id: "category-llm-fundamentals",
    order: 2,
    title: "AI & LLM Fundamentals",
    slug: "llm-fundamentals",
    description: "Mental models for how modern LLMs work — enough to reason about behavior, not to build one.",
    purpose: "Build accurate intuition about tokens, context, capabilities and limits.",
    track: "core",
    estimatedHours: 24,
    difficulty: { from: "beginner", to: "beginner" },
    topicIds: [
      "topic-llm-what-are",
      "topic-llm-tokens-context",
      "topic-llm-capabilities-limits",
      "topic-llm-landscape",
      "topic-llm-inference-params",
    ],
    projectIds: [],
    prerequisiteCategoryIds: [],
    learningGoals: [
      "Explain next-token prediction and inference",
      "Reason about tokens, context windows and cost",
      "Anticipate failure modes like hallucination",
      "Select models and tune inference parameters",
    ],
    whyItMatters: "You cannot engineer reliably around a black box you do not understand.",
  },
  {
    id: "category-llm-apis",
    order: 3,
    title: "LLM APIs & Prompt Engineering",
    slug: "llm-apis",
    description: "The workhorse skill — calling LLM APIs reliably and steering them with prompts and structured output.",
    purpose: "Build real API-backed features with structured output, streaming, resilience and cost control.",
    track: "core",
    estimatedHours: 36,
    difficulty: { from: "beginner", to: "intermediate" },
    topicIds: [
      "topic-api-first-call",
      "topic-api-prompting-core",
      "topic-api-reasoning-patterns",
      "topic-api-structured-output",
      "topic-api-streaming-robustness",
      "topic-api-conversation-state",
    ],
    projectIds: ["project-p1-structured-output"],
    prerequisiteCategoryIds: ["category-python-foundations", "category-llm-fundamentals"],
    learningGoals: [
      "Call chat APIs across providers including Azure OpenAI",
      "Engineer reliable prompts and reasoning patterns",
      "Produce schema-valid structured output",
      "Handle streaming, retries, and cost",
    ],
    whyItMatters: "This is roughly 80% of day-to-day AI engineering work.",
  },
  {
    id: "category-embeddings",
    order: 4,
    title: "Embeddings & Semantic Search",
    slug: "embeddings",
    description: "Represent meaning as vectors and search by similarity — the backbone of retrieval.",
    purpose: "Generate embeddings, measure similarity and build semantic search.",
    track: "core",
    estimatedHours: 28,
    difficulty: { from: "intermediate", to: "intermediate" },
    topicIds: [
      "topic-emb-concepts",
      "topic-emb-generate",
      "topic-emb-similarity",
      "topic-emb-chunking",
      "topic-emb-semantic-search-project",
    ],
    projectIds: ["project-p2-semantic-search"],
    prerequisiteCategoryIds: ["category-llm-fundamentals", "category-llm-apis"],
    learningGoals: [
      "Explain embedding space and distance metrics",
      "Generate and store embeddings efficiently",
      "Rank results by semantic similarity",
      "Chunk documents well for retrieval",
    ],
    whyItMatters: "Retrieval quality determines RAG quality.",
  },
  {
    id: "category-vector-databases",
    order: 5,
    title: "Vector Databases & Retrieval Infrastructure",
    slug: "vector-databases",
    description: "Store and query vectors at scale with metadata filtering and hybrid search.",
    purpose: "Move retrieval from in-memory arrays to real infrastructure.",
    track: "core",
    estimatedHours: 26,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-vdb-concepts",
      "topic-vdb-hands-on",
      "topic-vdb-metadata-hybrid",
      "topic-vdb-azure-search",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-embeddings"],
    learningGoals: [
      "Explain ANN tradeoffs and when a vector DB is needed",
      "Use a vector database (open-source and Azure AI Search)",
      "Apply metadata filtering and hybrid search",
      "Introduce reranking",
    ],
    whyItMatters: "Production retrieval needs real infrastructure, not in-memory arrays.",
  },
  {
    id: "category-rag",
    order: 6,
    title: "Retrieval-Augmented Generation (RAG)",
    slug: "rag",
    description: "Ground LLM answers in your data — the flagship AI-engineering pattern.",
    purpose: "Build, evaluate and harden RAG pipelines.",
    track: "core",
    estimatedHours: 40,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-rag-concepts",
      "topic-rag-basic-pipeline",
      "topic-rag-quality",
      "topic-rag-evaluation",
      "topic-rag-advanced-patterns",
    ],
    projectIds: ["project-p3-rag-app"],
    prerequisiteCategoryIds: ["category-embeddings", "category-vector-databases"],
    learningGoals: [
      "Build an end-to-end RAG pipeline with citations",
      "Improve retrieval quality with reranking and query rewriting",
      "Evaluate faithfulness and relevance",
      "Apply advanced RAG patterns selectively",
    ],
    whyItMatters: "It is the most common production AI use case.",
  },
  {
    id: "category-orchestration",
    order: 7,
    title: "Orchestration Frameworks (LangChain / LlamaIndex)",
    slug: "orchestration",
    description: "Use frameworks to compose LLM apps faster while understanding what they abstract.",
    purpose: "Build with LangChain/LlamaIndex/LangGraph and know when to go framework-free.",
    track: "core",
    estimatedHours: 30,
    difficulty: { from: "intermediate", to: "intermediate" },
    topicIds: [
      "topic-orch-why",
      "topic-orch-langchain",
      "topic-orch-llamaindex",
      "topic-orch-langgraph",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-rag"],
    learningGoals: [
      "Decide when a framework helps vs hides too much",
      "Rebuild RAG with LangChain idioms",
      "Use LlamaIndex for data-centric RAG",
      "Model stateful flows with LangGraph",
    ],
    whyItMatters: "Frameworks accelerate real work but must not become a crutch.",
  },
  {
    id: "category-agents",
    order: 8,
    title: "AI Agents & Tool Use",
    slug: "agents",
    description: "Systems where the LLM plans, calls tools and acts.",
    purpose: "Build reliable tool-using agents with guardrails and bounded autonomy.",
    track: "core",
    estimatedHours: 40,
    difficulty: { from: "advanced", to: "advanced" },
    topicIds: [
      "topic-agent-concepts",
      "topic-agent-tool-calling",
      "topic-agent-memory-planning",
      "topic-agent-frameworks-protocols",
      "topic-agent-multiagent",
    ],
    projectIds: ["project-p4-agent"],
    prerequisiteCategoryIds: ["category-llm-apis", "category-orchestration"],
    learningGoals: [
      "Explain the agent loop and when not to use agents",
      "Build robust tool/function calling",
      "Add memory, planning and termination limits",
      "Use agent frameworks and protocols (MCP)",
    ],
    whyItMatters: "The fastest-growing category of AI applications.",
  },
  {
    id: "category-multimodal",
    order: 9,
    title: "Multimodal AI",
    slug: "multimodal",
    description: "Work beyond text — vision, audio, speech and image generation.",
    purpose: "Build features using vision/audio/image APIs and open models.",
    track: "core",
    estimatedHours: 26,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-mm-vision",
      "topic-mm-speech-audio",
      "topic-mm-image-gen",
      "topic-mm-multimodal-rag",
    ],
    projectIds: ["project-p5-multimodal"],
    prerequisiteCategoryIds: ["category-llm-apis", "category-rag"],
    learningGoals: [
      "Extract structured data from images and documents",
      "Build speech-to-text / text-to-speech pipelines",
      "Integrate image generation with safety checks",
      "Build multimodal RAG over figures and tables",
    ],
    whyItMatters: "Modern products are increasingly multimodal.",
  },
  {
    id: "category-open-models",
    order: 10,
    title: "Open-Source Models & Hugging Face",
    slug: "open-models",
    description: "Use open models and run them locally or self-hosted.",
    purpose: "Run open models, use the HF ecosystem and serve OpenAI-compatible endpoints.",
    track: "core",
    estimatedHours: 28,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-oss-huggingface",
      "topic-oss-local-inference",
      "topic-oss-serving",
      "topic-oss-embeddings-local",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-llm-fundamentals", "category-embeddings"],
    learningGoals: [
      "Run inference with open models via Hugging Face",
      "Run quantized models locally",
      "Serve open models behind an OpenAI-compatible API",
      "Use local embeddings and rerankers",
    ],
    whyItMatters: "Cost, privacy, control and offline/enterprise scenarios.",
  },
  {
    id: "category-fine-tuning",
    order: 11,
    title: "Fine-Tuning & Model Adaptation",
    slug: "fine-tuning",
    description: "Adapt models when prompting/RAG isn't enough — conceptually deep, practically selective.",
    purpose: "Know when to fine-tune and run a practical hosted or LoRA fine-tune.",
    track: "optional-depth",
    estimatedHours: 30,
    difficulty: { from: "advanced", to: "advanced" },
    topicIds: [
      "topic-ft-when",
      "topic-ft-data",
      "topic-ft-hosted",
      "topic-ft-lora",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-rag", "category-open-models"],
    learningGoals: [
      "Decide when fine-tuning is warranted vs prompt/RAG",
      "Build clean fine-tuning datasets",
      "Run and evaluate a hosted fine-tune",
      "Run a small PEFT/LoRA fine-tune",
    ],
    whyItMatters: "Occasionally necessary; more often the wrong first tool. Excluded from primary progress.",
  },
  {
    id: "category-evaluation",
    order: 12,
    title: "AI Evaluation, Observability & Quality",
    slug: "evaluation",
    description: "Measure and monitor AI quality — the difference between a demo and a product.",
    purpose: "Build evals, trace/observe LLM apps and catch regressions.",
    track: "core",
    estimatedHours: 30,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-eval-why",
      "topic-eval-methods",
      "topic-eval-observability",
      "topic-eval-ci",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-llm-apis", "category-rag"],
    learningGoals: [
      "Frame evaluation for generative systems",
      "Implement automated and human evaluation",
      "Instrument tracing, cost and latency",
      "Gate regressions with eval in CI",
    ],
    whyItMatters: "You cannot improve or trust what you do not measure.",
  },
  {
    id: "category-ai-security",
    order: 13,
    title: "AI Security & Safety",
    slug: "ai-security",
    description: "Defend AI apps against AI-specific threats and use models safely.",
    purpose: "Mitigate prompt injection, secure tools/data and apply guardrails (OWASP LLM Top 10).",
    track: "core",
    estimatedHours: 26,
    difficulty: { from: "intermediate", to: "advanced" },
    topicIds: [
      "topic-sec-threat-model",
      "topic-sec-prompt-injection",
      "topic-sec-guardrails",
      "topic-sec-data-privacy",
    ],
    projectIds: [],
    prerequisiteCategoryIds: ["category-llm-apis", "category-agents"],
    learningGoals: [
      "Threat-model an LLM application",
      "Defend against prompt injection",
      "Add guardrails, moderation and safe output handling",
      "Handle secrets, PII and data residency",
    ],
    whyItMatters: "LLM apps have a unique, serious attack surface.",
  },
  {
    id: "category-production",
    order: 14,
    title: "Deployment & Production AI Engineering",
    slug: "production",
    description: "Ship, scale and operate AI apps — Docker, APIs, cloud and Azure depth.",
    purpose: "Build an API, containerize, deploy to cloud/Azure, and add CI/CD and monitoring.",
    track: "core",
    estimatedHours: 44,
    difficulty: { from: "advanced", to: "advanced" },
    topicIds: [
      "topic-prod-api",
      "topic-prod-docker",
      "topic-prod-cloud-deploy",
      "topic-prod-azure-ai",
      "topic-prod-cicd-ops",
      "topic-prod-scaling-cost",
    ],
    projectIds: ["project-p6-production-service"],
    prerequisiteCategoryIds: ["category-evaluation", "category-ai-security"],
    learningGoals: [
      "Serve an AI app as a robust streaming API",
      "Containerize and deploy to the cloud",
      "Assemble an enterprise Azure AI stack",
      "Automate CI/CD, monitoring and cost control",
    ],
    whyItMatters: "This is what separates an AI Engineer from a notebook tinkerer.",
  },
  {
    id: "category-advanced",
    order: 15,
    title: "Advanced Topics & Specialization",
    slug: "advanced",
    description: "Frontier and specialization topics — pursue selectively after the core path.",
    purpose: "Stay current and specialize without diluting the core.",
    track: "optional-depth",
    estimatedHours: 30,
    difficulty: { from: "advanced", to: "advanced" },
    topicIds: [
      "topic-adv-context-engineering",
      "topic-adv-reasoning-models",
      "topic-adv-ml-literacy",
      "topic-adv-emerging",
      "topic-adv-specialization-capstone",
    ],
    projectIds: ["project-p7-specialization"],
    prerequisiteCategoryIds: ["category-production"],
    learningGoals: [
      "Apply context engineering and long-context tradeoffs",
      "Evaluate reasoning models and test-time compute",
      "Acquire just-enough ML literacy",
      "Maintain a continuous-learning practice",
    ],
    whyItMatters: "Keeps you current and enables specialization. Excluded from primary progress.",
  },
];
