import type { Project } from "./types";

// 7 projects — locked ordering (P1..P7) preserved. P1–P6 are core; P7 is
// optional-depth. All reference existing curriculum topics. No invented projects.
export const projects: Project[] = [
  {
    id: "project-p1-structured-output",
    number: 1,
    title: "LLM-Powered Structured-Output Utility",
    slug: "structured-output-utility",
    description: "A useful single-purpose LLM tool that produces validated structured output with robust API handling.",
    objective: "Ship a CLI/API tool that extracts validated JSON with retries, streaming and cost tracking — demonstrating reliability engineering, not prompt-calling.",
    difficulty: { from: "beginner", to: "intermediate" },
    estimatedHours: 12,
    track: "core",
    technologies: ["Python", "OpenAI", "Azure OpenAI", "pydantic"],
    skillsCovered: ["skill-llm-apis", "skill-structured-outputs", "skill-resilience", "skill-azure-ai"],
    prerequisiteTopicIds: ["topic-api-first-call", "topic-api-structured-output", "topic-api-streaming-robustness"],
    relatedTopicIds: ["topic-api-first-call", "topic-api-prompting-core", "topic-api-structured-output", "topic-api-streaming-robustness", "topic-api-conversation-state"],
    milestoneIds: ["milestone-p1-01", "milestone-p1-02", "milestone-p1-03", "milestone-p1-04", "milestone-p1-05"],
    expectedDeliverables: ["CLI + config", "Validated JSON output (pydantic)", "README", "Cost logging"],
    portfolioValue: "Shows reliable API engineering — validated outputs, resilience and cost awareness — not a toy prompt.",
    categoryId: "category-llm-apis",
  },
  {
    id: "project-p2-semantic-search",
    number: 2,
    title: "Semantic Search Engine over Your Own Data",
    slug: "semantic-search-engine",
    description: "Evolve the semantic-search core from topic 4.5 into a polished retrieval product with infrastructure and hybrid search.",
    objective: "Take the existing semantic-search core and add a vector database, metadata filtering, hybrid search, reranking and documentation — without rebuilding it.",
    difficulty: { from: "intermediate", to: "intermediate" },
    estimatedHours: 14,
    track: "core",
    technologies: ["Python", "sentence-transformers / OpenAI / Azure embeddings", "Qdrant / pgvector / Azure AI Search"],
    skillsCovered: ["skill-semantic-search", "skill-embeddings", "skill-chunking", "skill-vector-databases", "skill-hybrid-search"],
    prerequisiteTopicIds: ["topic-emb-semantic-search-project", "topic-vdb-hands-on", "topic-vdb-metadata-hybrid"],
    relatedTopicIds: ["topic-emb-similarity", "topic-emb-chunking", "topic-emb-semantic-search-project", "topic-vdb-hands-on", "topic-vdb-metadata-hybrid", "topic-vdb-azure-search"],
    milestoneIds: ["milestone-p2-01", "milestone-p2-02", "milestone-p2-03", "milestone-p2-04", "milestone-p2-05"],
    expectedDeliverables: ["Ingestion pipeline", "Vector DB store", "Hybrid + filtered search", "Search UI/CLI", "Documentation"],
    portfolioValue: "Demonstrates real retrieval infrastructure and measurable search-quality tuning.",
    evolvesFrom: { topicId: "topic-emb-semantic-search-project", artifact: "semantic-search-core" },
    categoryId: "category-embeddings",
  },
  {
    id: "project-p3-rag-app",
    number: 3,
    title: "Production-Style RAG Application",
    slug: "rag-application",
    description: "A grounded Q&A system over a real document set with citations, evaluation and an API.",
    objective: "Build the canonical AI-engineer deliverable: a grounded, evaluated, served RAG app — not a demo notebook.",
    difficulty: { from: "intermediate", to: "advanced" },
    estimatedHours: 22,
    track: "core",
    technologies: ["Python", "LangChain / LlamaIndex", "Vector DB / Azure AI Search", "FastAPI", "Ragas-style eval"],
    skillsCovered: ["skill-rag", "skill-retrieval-quality", "skill-hybrid-search", "skill-evaluation", "skill-fastapi"],
    prerequisiteTopicIds: ["topic-rag-basic-pipeline", "topic-rag-quality", "topic-rag-evaluation", "topic-rag-advanced-patterns"],
    relatedTopicIds: ["topic-rag-concepts", "topic-rag-basic-pipeline", "topic-rag-quality", "topic-rag-evaluation", "topic-rag-advanced-patterns", "topic-orch-langchain", "topic-vdb-azure-search"],
    milestoneIds: ["milestone-p3-01", "milestone-p3-02", "milestone-p3-03", "milestone-p3-04", "milestone-p3-05"],
    expectedDeliverables: ["Full RAG pipeline", "Source citations", "Eval harness", "FastAPI service", "Basic UI"],
    portfolioValue: "The canonical AI-engineer deliverable — grounded, evaluated and served, reused by Project P6.",
    categoryId: "category-rag",
  },
  {
    id: "project-p4-agent",
    number: 4,
    title: "Tool-Using Agent",
    slug: "tool-using-agent",
    description: "An agent that reliably uses multiple real tools to complete multi-step tasks with guardrails.",
    objective: "Demonstrate control over autonomy: reliable tool use, memory, termination, cost bounds and security.",
    difficulty: { from: "advanced", to: "advanced" },
    estimatedHours: 22,
    track: "core",
    technologies: ["Python", "LangGraph / agent framework", "MCP (optional)", "tracing"],
    skillsCovered: ["skill-agents", "skill-tool-calling", "skill-mcp", "skill-prompt-injection", "skill-guardrails"],
    prerequisiteTopicIds: ["topic-agent-tool-calling", "topic-agent-memory-planning", "topic-sec-guardrails"],
    relatedTopicIds: ["topic-agent-concepts", "topic-agent-tool-calling", "topic-agent-memory-planning", "topic-agent-frameworks-protocols", "topic-agent-multiagent", "topic-sec-prompt-injection", "topic-sec-guardrails"],
    milestoneIds: ["milestone-p4-01", "milestone-p4-02", "milestone-p4-03", "milestone-p4-04", "milestone-p4-05"],
    expectedDeliverables: ["Agent with 3+ tools", "Step/cost limits", "Injection defenses", "Traces"],
    portfolioValue: "Shows bounded autonomy — termination, cost limits and security — which most agent demos lack.",
    categoryId: "category-agents",
  },
  {
    id: "project-p5-multimodal",
    number: 5,
    title: "Multimodal Application",
    slug: "multimodal-application",
    description: "A non-chat multimodal feature — a document/image understanding pipeline or voice assistant with retrieval.",
    objective: "Demonstrate breadth beyond text with real document/media engineering and edge-case robustness.",
    difficulty: { from: "advanced", to: "advanced" },
    estimatedHours: 18,
    track: "core",
    technologies: ["Vision / STT / TTS APIs or open models", "RAG stack"],
    skillsCovered: ["skill-multimodal", "skill-rag", "skill-structured-outputs"],
    prerequisiteTopicIds: ["topic-mm-vision", "topic-mm-multimodal-rag"],
    relatedTopicIds: ["topic-mm-vision", "topic-mm-speech-audio", "topic-mm-image-gen", "topic-mm-multimodal-rag", "topic-rag-basic-pipeline"],
    milestoneIds: ["milestone-p5-01", "milestone-p5-02", "milestone-p5-03", "milestone-p5-04"],
    expectedDeliverables: ["Multimodal pipeline (media in → structured/answer out)", "Edge-case evaluation"],
    portfolioValue: "Demonstrates breadth beyond text and real document/media engineering.",
    categoryId: "category-multimodal",
  },
  {
    id: "project-p6-production-service",
    number: 6,
    title: "Production-Grade AI Service (Capstone Integration)",
    slug: "production-ai-service",
    description: "Take P3/P4 to production: containerized, deployed on Azure, with CI/CD, monitoring, eval gates and cost controls.",
    objective: "Prove you can operate AI in production — the strongest hiring signal.",
    difficulty: { from: "advanced", to: "advanced" },
    estimatedHours: 28,
    track: "core",
    technologies: ["FastAPI", "Docker", "Azure (Container Apps, OpenAI, AI Search, Key Vault)", "CI/CD", "tracing"],
    skillsCovered: ["skill-fastapi", "skill-docker", "skill-cloud-deployment", "skill-azure-ai", "skill-llmops", "skill-observability", "skill-cost-optimization", "skill-ai-security"],
    prerequisiteTopicIds: ["topic-prod-api", "topic-prod-docker", "topic-prod-cloud-deploy", "topic-prod-azure-ai", "topic-prod-cicd-ops"],
    relatedTopicIds: ["topic-prod-api", "topic-prod-docker", "topic-prod-cloud-deploy", "topic-prod-azure-ai", "topic-prod-cicd-ops", "topic-prod-scaling-cost", "topic-eval-ci", "topic-eval-observability", "topic-rag-advanced-patterns"],
    milestoneIds: ["milestone-p6-01", "milestone-p6-02", "milestone-p6-03", "milestone-p6-04", "milestone-p6-05", "milestone-p6-06"],
    expectedDeliverables: ["Dockerized API", "Azure deployment (Key Vault / managed identity)", "CI/CD with eval gate", "Monitoring dashboard", "Cost/caching optimization", "Security review"],
    portfolioValue: "The flagship — proves you can operate AI in production, the strongest hiring signal.",
    categoryId: "category-production",
  },
  {
    id: "project-p7-specialization",
    number: 7,
    title: "Specialization Capstone",
    slug: "specialization-capstone",
    description: "A self-directed advanced system in a chosen niche.",
    objective: "Differentiate with depth in a chosen direction and polish the portfolio.",
    difficulty: { from: "advanced", to: "advanced" },
    estimatedHours: 20,
    track: "optional-depth",
    technologies: ["Depends on chosen niche"],
    skillsCovered: ["skill-continuous-learning", "skill-context-engineering"],
    prerequisiteTopicIds: ["topic-adv-specialization-capstone"],
    relatedTopicIds: ["topic-adv-context-engineering", "topic-adv-specialization-capstone"],
    milestoneIds: ["milestone-p7-01", "milestone-p7-02", "milestone-p7-03"],
    expectedDeliverables: ["Advanced niche project", "Write-up", "Portfolio polish"],
    portfolioValue: "Differentiation and depth in a chosen direction.",
    categoryId: "category-advanced",
  },
];
