import type { Resource } from "./types";

// Placeholder-safe resources. The locked curriculum did not specify concrete URLs,
// so every entry uses url: null and status: "placeholder" ("reference needed").
// The application renders these as a reference state; real URLs can be filled later
// without changing IDs. No URLs are fabricated.
export const resources: Resource[] = [
  { id: "resource-python-official-docs", title: "Python Official Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-core-syntax" },
  { id: "resource-json-handling-guide", title: "Working with JSON in Python", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-data-structures" },
  { id: "resource-venv-dotenv-guide", title: "Virtual Environments & Secrets Guide", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-env-tooling" },
  { id: "resource-git-actions-basics", title: "Git & GitHub Actions Basics", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-env-tooling" },
  { id: "resource-httpx-docs", title: "httpx / requests Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-async-http" },
  { id: "resource-pandas-intro", title: "pandas / numpy Essentials", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-py-data-libs" },
  { id: "resource-llm-conceptual-overview", title: "How LLMs Work (Conceptual Overview)", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-llm-what-are" },
  { id: "resource-tokenizer-tool", title: "Tokenizer / Token Counting Tool", type: "tool", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-llm-tokens-context" },
  { id: "resource-inference-params-guide", title: "Sampling Parameters Explained", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-llm-inference-params" },
  { id: "resource-chat-api-docs", title: "Chat Completions API Reference", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-api-first-call" },
  { id: "resource-azure-openai-docs", title: "Azure OpenAI Service Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-api-first-call" },
  { id: "resource-prompting-guide", title: "Prompt Engineering Guide", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-api-prompting-core" },
  { id: "resource-structured-outputs-docs", title: "Structured Outputs & Function Calling Docs", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-api-structured-output" },
  { id: "resource-pydantic-docs", title: "pydantic Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-api-structured-output" },
  { id: "resource-embeddings-guide", title: "Embeddings Concepts & Metrics", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-emb-concepts" },
  { id: "resource-chunking-strategies", title: "Chunking Strategies Reference", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-emb-chunking" },
  { id: "resource-vector-db-docs", title: "Vector Database Documentation (Qdrant/pgvector/Chroma)", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-vdb-hands-on" },
  { id: "resource-azure-ai-search-docs", title: "Azure AI Search Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-vdb-azure-search" },
  { id: "resource-rag-overview", title: "Retrieval-Augmented Generation Overview", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-rag-concepts" },
  { id: "resource-rag-eval-framework", title: "RAG Evaluation Framework (Ragas-style)", type: "tool", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-rag-evaluation" },
  { id: "resource-langchain-docs", title: "LangChain Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-orch-langchain" },
  { id: "resource-llamaindex-docs", title: "LlamaIndex Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-orch-llamaindex" },
  { id: "resource-langgraph-docs", title: "LangGraph Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-orch-langgraph" },
  { id: "resource-agent-patterns", title: "Agent Architectures & Patterns", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-agent-concepts" },
  { id: "resource-mcp-docs", title: "Model Context Protocol Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-agent-frameworks-protocols" },
  { id: "resource-vision-api-docs", title: "Vision Model API Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-mm-vision" },
  { id: "resource-speech-api-docs", title: "Speech (STT/TTS) API Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-mm-speech-audio" },
  { id: "resource-huggingface-docs", title: "Hugging Face Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-oss-huggingface" },
  { id: "resource-ollama-docs", title: "Local Inference (Ollama / llama.cpp) Docs", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-oss-local-inference" },
  { id: "resource-vllm-docs", title: "Model Serving (vLLM / TGI) Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-oss-serving" },
  { id: "resource-finetuning-guide", title: "Fine-Tuning Decision & Workflow Guide", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-ft-when" },
  { id: "resource-peft-lora-guide", title: "PEFT / LoRA / QLoRA Guide", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-ft-lora" },
  { id: "resource-eval-methods-guide", title: "LLM Evaluation Methods & Metrics", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-eval-methods" },
  { id: "resource-observability-tools", title: "LLM Observability Tools (LangSmith/Langfuse)", type: "tool", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-eval-observability" },
  { id: "resource-owasp-llm-top10", title: "OWASP Top 10 for LLM Applications", type: "reference", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-sec-threat-model" },
  { id: "resource-prompt-injection-guide", title: "Prompt Injection Attacks & Defenses", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-sec-prompt-injection" },
  { id: "resource-fastapi-docs", title: "FastAPI Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-prod-api" },
  { id: "resource-docker-docs", title: "Docker Documentation", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-prod-docker" },
  { id: "resource-azure-container-apps", title: "Azure Container Apps & Key Vault Docs", type: "documentation", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-prod-azure-ai" },
  { id: "resource-cicd-guide", title: "CI/CD & LLMOps Guide", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-prod-cicd-ops" },
  { id: "resource-context-engineering", title: "Context Engineering Patterns", type: "article", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-adv-context-engineering" },
  { id: "resource-ml-literacy", title: "Just-Enough ML Concepts", type: "guide", url: null, status: "placeholder", source: "Curriculum reference", topicId: "topic-adv-ml-literacy" },
];
