import type { Skill } from "./types";

// Normalized skill taxonomy derived ONLY from the locked curriculum.
export const skills: Skill[] = [
  { id: "skill-python", name: "Python for AI", description: "Scoped Python fluency for building AI systems (syntax, data, modules).", relatedTopicIds: ["topic-py-core-syntax", "topic-py-data-structures", "topic-py-functions-modules", "topic-py-optional-depth"] },
  { id: "skill-data-handling", name: "Data & JSON Handling", description: "Working with nested/JSON data and preparing text corpora.", relatedTopicIds: ["topic-py-data-structures", "topic-py-data-libs", "topic-emb-chunking"] },
  { id: "skill-env-tooling", name: "Environments & Secrets", description: "Virtual envs, dependency management, and safe secret handling.", relatedTopicIds: ["topic-py-env-tooling", "topic-sec-data-privacy"] },
  { id: "skill-git-cicd", name: "Git & CI/CD Fundamentals", description: "Git workflow, branches, PRs, GitHub Actions, CI vs CD, pipelines.", relatedTopicIds: ["topic-py-env-tooling", "topic-prod-cicd-ops", "topic-eval-ci"] },
  { id: "skill-http-async", name: "HTTP & Async", description: "Calling REST APIs reliably, async/await, retries and timeouts.", relatedTopicIds: ["topic-py-async-http", "topic-api-first-call", "topic-py-errors-logging"] },
  { id: "skill-observability-basics", name: "Errors, Logging & Debugging", description: "Exception handling, structured logging, and debugging workflows.", relatedTopicIds: ["topic-py-errors-logging"] },
  { id: "skill-llm-fundamentals", name: "LLM Fundamentals", description: "Mental models of how LLMs work, tokens, context, capabilities and limits.", relatedTopicIds: ["topic-llm-what-are", "topic-llm-tokens-context", "topic-llm-capabilities-limits", "topic-llm-landscape", "topic-llm-inference-params"] },
  { id: "skill-tokenization", name: "Tokens & Context Management", description: "Token counting, context windows, cost estimation and trimming.", relatedTopicIds: ["topic-llm-tokens-context", "topic-api-conversation-state"] },
  { id: "skill-model-selection", name: "Model Selection", description: "Choosing models on cost, quality, latency and licensing.", relatedTopicIds: ["topic-llm-landscape", "topic-prod-scaling-cost"] },
  { id: "skill-llm-apis", name: "LLM APIs", description: "Calling chat/completion APIs across providers including Azure OpenAI.", relatedTopicIds: ["topic-api-first-call", "topic-api-streaming-robustness", "topic-api-conversation-state"] },
  { id: "skill-prompt-engineering", name: "Prompt Engineering", description: "System prompts, few-shot, delimiters, reasoning patterns and iteration.", relatedTopicIds: ["topic-api-prompting-core", "topic-api-reasoning-patterns"] },
  { id: "skill-structured-outputs", name: "Structured Outputs & Tool Calling", description: "Schema-valid JSON, structured outputs, and function/tool calling basics.", relatedTopicIds: ["topic-api-structured-output", "topic-agent-tool-calling"] },
  { id: "skill-resilience", name: "Streaming & Resilience", description: "Streaming, retries/backoff, caching and cost control for LLM apps.", relatedTopicIds: ["topic-api-streaming-robustness", "topic-prod-scaling-cost"] },
  { id: "skill-embeddings", name: "Embeddings", description: "Generating embeddings and reasoning about vector space and metrics.", relatedTopicIds: ["topic-emb-concepts", "topic-emb-generate", "topic-emb-similarity", "topic-oss-embeddings-local"] },
  { id: "skill-semantic-search", name: "Semantic Search", description: "Similarity ranking and building semantic search systems.", relatedTopicIds: ["topic-emb-similarity", "topic-emb-semantic-search-project"] },
  { id: "skill-chunking", name: "Chunking & Text Prep", description: "Document splitting strategies and metadata for retrieval.", relatedTopicIds: ["topic-emb-chunking"] },
  { id: "skill-vector-databases", name: "Vector Databases", description: "Storing/querying vectors at scale with ANN indexes.", relatedTopicIds: ["topic-vdb-concepts", "topic-vdb-hands-on", "topic-vdb-azure-search"] },
  { id: "skill-hybrid-search", name: "Hybrid Search & Reranking", description: "Metadata filtering, keyword+vector fusion, and rerankers.", relatedTopicIds: ["topic-vdb-metadata-hybrid", "topic-rag-quality", "topic-oss-embeddings-local"] },
  { id: "skill-rag", name: "Retrieval-Augmented Generation", description: "Building grounded RAG pipelines with citations.", relatedTopicIds: ["topic-rag-concepts", "topic-rag-basic-pipeline", "topic-rag-advanced-patterns", "topic-mm-multimodal-rag"] },
  { id: "skill-retrieval-quality", name: "Retrieval Quality", description: "Reranking, query rewriting and diagnosing retrieval vs generation failures.", relatedTopicIds: ["topic-rag-quality"] },
  { id: "skill-evaluation", name: "AI Evaluation", description: "Faithfulness/relevance metrics, LLM-as-judge, golden sets and eval harnesses.", relatedTopicIds: ["topic-rag-evaluation", "topic-eval-why", "topic-eval-methods", "topic-eval-ci"] },
  { id: "skill-observability", name: "Observability & Tracing", description: "Tracing LLM calls, cost/latency/quality dashboards and feedback capture.", relatedTopicIds: ["topic-eval-observability", "topic-prod-cicd-ops"] },
  { id: "skill-orchestration", name: "Orchestration Frameworks", description: "LangChain/LlamaIndex/LangGraph composition and stateful flows.", relatedTopicIds: ["topic-orch-why", "topic-orch-langchain", "topic-orch-llamaindex", "topic-orch-langgraph"] },
  { id: "skill-agents", name: "AI Agents", description: "Agent loops, planning, memory and bounded autonomy.", relatedTopicIds: ["topic-agent-concepts", "topic-agent-memory-planning", "topic-agent-multiagent"] },
  { id: "skill-tool-calling", name: "Tool / Function Calling", description: "Robust tool schemas, argument validation and execution loops.", relatedTopicIds: ["topic-agent-tool-calling", "topic-agent-frameworks-protocols"] },
  { id: "skill-mcp", name: "Agent Protocols (MCP)", description: "Interoperable tool use via the Model Context Protocol and frameworks.", relatedTopicIds: ["topic-agent-frameworks-protocols"] },
  { id: "skill-multimodal", name: "Multimodal AI", description: "Vision, speech/audio, image generation and multimodal retrieval.", relatedTopicIds: ["topic-mm-vision", "topic-mm-speech-audio", "topic-mm-image-gen", "topic-mm-multimodal-rag"] },
  { id: "skill-open-models", name: "Open-Source Models", description: "Hugging Face ecosystem, local inference and quantization.", relatedTopicIds: ["topic-oss-huggingface", "topic-oss-local-inference", "topic-oss-embeddings-local"] },
  { id: "skill-model-serving", name: "Model Serving", description: "Serving open models behind OpenAI-compatible endpoints.", relatedTopicIds: ["topic-oss-serving"] },
  { id: "skill-fine-tuning", name: "Fine-Tuning & Adaptation", description: "When to fine-tune, dataset design, hosted and PEFT/LoRA fine-tuning.", relatedTopicIds: ["topic-ft-when", "topic-ft-data", "topic-ft-hosted", "topic-ft-lora"] },
  { id: "skill-ai-security", name: "AI Security", description: "LLM threat modeling and OWASP LLM Top 10 defenses.", relatedTopicIds: ["topic-sec-threat-model", "topic-sec-data-privacy"] },
  { id: "skill-prompt-injection", name: "Prompt Injection Defense", description: "Direct/indirect injection attacks and layered mitigations.", relatedTopicIds: ["topic-sec-prompt-injection"] },
  { id: "skill-guardrails", name: "Guardrails & Safe Output", description: "Moderation, output validation, PII handling and safe tool execution.", relatedTopicIds: ["topic-sec-guardrails"] },
  { id: "skill-fastapi", name: "Serving AI as an API", description: "Building production APIs (FastAPI) around AI apps with streaming.", relatedTopicIds: ["topic-prod-api"] },
  { id: "skill-docker", name: "Containerization", description: "Dockerfiles, images, compose and lean AI service containers.", relatedTopicIds: ["topic-prod-docker"] },
  { id: "skill-cloud-deployment", name: "Cloud Deployment", description: "Deploying containers to managed cloud services with config and logs.", relatedTopicIds: ["topic-prod-cloud-deploy"] },
  { id: "skill-azure-ai", name: "Azure AI Platform", description: "Azure OpenAI, AI Search, Foundry, Container Apps, Key Vault and identity.", relatedTopicIds: ["topic-vdb-azure-search", "topic-prod-azure-ai", "topic-ft-hosted"] },
  { id: "skill-llmops", name: "LLMOps & CI/CD", description: "Automated deploy, monitoring, eval gates, rollback and prompt versioning.", relatedTopicIds: ["topic-prod-cicd-ops", "topic-eval-ci"] },
  { id: "skill-cost-optimization", name: "Scaling & Cost Optimization", description: "Caching, batching, model routing/fallback and latency/cost tuning.", relatedTopicIds: ["topic-prod-scaling-cost"] },
  { id: "skill-context-engineering", name: "Context Engineering", description: "Context assembly, long-context vs RAG tradeoffs and prompt/context caching.", relatedTopicIds: ["topic-adv-context-engineering"] },
  { id: "skill-ml-literacy", name: "ML Literacy", description: "Just-enough conceptual ML (training, overfitting) with no derivations.", relatedTopicIds: ["topic-adv-ml-literacy", "topic-adv-reasoning-models"] },
  { id: "skill-continuous-learning", name: "Staying Current", description: "Tracking emerging patterns, protocols and modalities responsibly.", relatedTopicIds: ["topic-adv-emerging", "topic-adv-specialization-capstone"] },
];
