import type { Topic } from "./types";

// Topics for categories 1–6. Locked ordering preserved. recommendedAfter is
// ADVISORY only (no hard lock). CORE/USEFUL/OPTIONAL DEPTH classifications match
// the locked curriculum.
export const topicsPartA: Topic[] = [
  // ── Category 1 · Python Foundations ─────────────────────────────────────────
  {
    id: "topic-py-core-syntax",
    categoryId: "category-python-foundations",
    order: 1,
    title: "Python Essentials",
    slug: "python-essentials",
    shortDescription: "Variables, types, control flow, functions and comprehensions — enough to be productive.",
    whyItMatters: "You need to write small scripts fluently before assembling AI systems.",
    learningObjectives: ["Write functions and use lists/dicts/sets", "Use comprehensions and f-strings", "Read basic Python without lookups"],
    concepts: ["types", "control flow", "functions", "comprehensions", "truthiness"],
    commonMistakes: ["Mutable default arguments", "Confusing is vs ==", "Over-nesting logic"],
    masteryCriteria: "You can write a small script without looking up syntax.",
    difficulty: "beginner",
    estimatedHours: 6,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: [],
    skillIds: ["skill-python"],
    unitIds: ["unit-py-core-syntax-01", "unit-py-core-syntax-02", "unit-py-core-syntax-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-data-structures",
    categoryId: "category-python-foundations",
    order: 2,
    title: "Data Handling & JSON",
    slug: "data-handling-json",
    shortDescription: "Dicts/lists deeply, JSON in/out, and working with nested API-shaped data.",
    whyItMatters: "AI APIs speak JSON; reshaping nested data is a constant task.",
    learningObjectives: ["Navigate nested JSON", "Serialize/deserialize data", "Transform records safely"],
    concepts: ["JSON module", "nested access", "list/dict manipulation", "enumerate/zip"],
    commonMistakes: ["KeyError vs .get()", "Mutating while iterating"],
    masteryCriteria: "You can reshape a messy JSON API response into a clean structure.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-py-core-syntax"],
    skillIds: ["skill-python", "skill-data-handling"],
    unitIds: ["unit-py-data-structures-01", "unit-py-data-structures-02", "unit-py-data-structures-03", "unit-py-data-structures-04"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-functions-modules",
    categoryId: "category-python-foundations",
    order: 3,
    title: "Functions, Modules & Project Layout",
    slug: "functions-modules-layout",
    shortDescription: "Reusable functions, modules/packages, imports and a sane project structure.",
    whyItMatters: "AI projects grow fast; structure keeps them maintainable.",
    learningObjectives: ["Organize code into modules", "Understand __main__", "Use type hints and docstrings"],
    concepts: ["modules/packages", "imports", "type hints", "docstrings"],
    commonMistakes: ["Circular imports", "Everything in one file"],
    masteryCriteria: "You can structure a small multi-file project cleanly.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-py-core-syntax"],
    skillIds: ["skill-python"],
    unitIds: ["unit-py-functions-modules-01", "unit-py-functions-modules-02", "unit-py-functions-modules-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-env-tooling",
    categoryId: "category-python-foundations",
    order: 4,
    title: "Environments, Packages, Secrets & Git/CI",
    slug: "env-tooling-git-ci",
    shortDescription: "venv, pip, requirements, dotenv, safe API keys, plus Git workflow and GitHub Actions basics.",
    whyItMatters: "Reproducible environments, safe secrets and version control are table stakes for shipping.",
    learningObjectives: ["Create isolated environments", "Load secrets from env vars", "Use Git branches/commits/PRs", "Run a basic GitHub Actions workflow"],
    concepts: ["venv", "pip", "dotenv", "os.environ", "git workflow", "branches", "pull requests", "GitHub Actions", "CI vs CD", "pipelines"],
    commonMistakes: ["Hardcoding API keys", "Committing .env", "Committing directly to main"],
    masteryCriteria: "You spin up a reproducible env, load a secret safely, and open a PR that triggers CI.",
    difficulty: "beginner",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-py-core-syntax"],
    skillIds: ["skill-env-tooling", "skill-git-cicd"],
    unitIds: ["unit-py-env-tooling-01", "unit-py-env-tooling-02", "unit-py-env-tooling-03", "unit-py-env-tooling-04", "unit-py-env-tooling-05"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-async-http",
    categoryId: "category-python-foundations",
    order: 5,
    title: "HTTP, Async & API Calls",
    slug: "http-async-apis",
    shortDescription: "requests/httpx, REST basics, JSON APIs and an intro to async for concurrent calls.",
    whyItMatters: "Every LLM call is an API call; resilience and concurrency matter.",
    learningObjectives: ["Call REST APIs and handle errors", "Use async/await basics", "Add retries and timeouts"],
    concepts: ["HTTP verbs", "headers/auth", "retries", "async/await", "rate limits"],
    commonMistakes: ["Ignoring errors/timeouts", "Blocking loops where async helps"],
    masteryCriteria: "You call a paginated API with retries and parse the results.",
    difficulty: "beginner",
    estimatedHours: 6,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-py-data-structures", "topic-py-env-tooling"],
    skillIds: ["skill-http-async"],
    unitIds: ["unit-py-async-http-01", "unit-py-async-http-02", "unit-py-async-http-03", "unit-py-async-http-04"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-errors-logging",
    categoryId: "category-python-foundations",
    order: 6,
    title: "Errors, Logging & Debugging",
    slug: "errors-logging-debugging",
    shortDescription: "Exceptions, try/except patterns, logging over print and basic debugging.",
    whyItMatters: "AI apps fail in messy ways; graceful handling and logs are essential.",
    learningObjectives: ["Handle errors gracefully", "Use structured logging", "Read tracebacks"],
    concepts: ["exceptions", "custom errors", "logging", "debugging workflow"],
    commonMistakes: ["Bare except:", "Swallowing errors", "Print-debugging everything"],
    masteryCriteria: "You add proper error handling and logging to an API client.",
    difficulty: "beginner",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-py-functions-modules"],
    skillIds: ["skill-observability-basics"],
    unitIds: ["unit-py-errors-logging-01", "unit-py-errors-logging-02", "unit-py-errors-logging-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-data-libs",
    categoryId: "category-python-foundations",
    order: 7,
    title: "Practical Data Tooling (pandas/numpy, light)",
    slug: "data-tooling",
    shortDescription: "Just-enough pandas/numpy for loading, inspecting and preparing text/data for AI.",
    whyItMatters: "You will load and clean datasets before embedding or evaluation.",
    learningObjectives: ["Load CSV/JSON into DataFrames", "Filter and select data", "Use basic numpy arrays"],
    concepts: ["DataFrame", "Series", "indexing", "numpy arrays/vectors"],
    commonMistakes: ["Chained-assignment warnings", "Treating pandas as mandatory everywhere"],
    masteryCriteria: "You load and clean a dataset ready for embedding.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-py-data-structures"],
    skillIds: ["skill-data-handling"],
    unitIds: ["unit-py-data-libs-01", "unit-py-data-libs-02", "unit-py-data-libs-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-py-optional-depth",
    categoryId: "category-python-foundations",
    order: 8,
    title: "Optional General Python & CS Depth",
    slug: "python-optional-depth",
    shortDescription: "OOP depth, decorators, generators, typing internals, testing, packaging — only when a real need appears.",
    whyItMatters: "Occasionally useful, but front-loading it delays building AI apps.",
    learningObjectives: ["Deepen language mastery only when relevant"],
    concepts: ["classes/inheritance", "decorators", "generators", "pytest", "packaging"],
    commonMistakes: ["Front-loading this before building AI apps"],
    masteryCriteria: "Reference track — not a gate; consult when a real need arises.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-py-functions-modules"],
    skillIds: ["skill-python"],
    unitIds: ["unit-py-optional-depth-01", "unit-py-optional-depth-02"],
    relatedProjectIds: [],
  },

  // ── Category 2 · AI & LLM Fundamentals ──────────────────────────────────────
  {
    id: "topic-llm-what-are",
    categoryId: "category-llm-fundamentals",
    order: 1,
    title: "What LLMs Are (and Aren't)",
    slug: "what-llms-are",
    shortDescription: "Transformers at a conceptual level, next-token prediction, training vs inference — no math.",
    whyItMatters: "Accurate mental models prevent whole classes of engineering mistakes.",
    learningObjectives: ["Explain next-token prediction", "Distinguish pretraining, fine-tuning and inference"],
    concepts: ["transformer (conceptual)", "pretraining", "inference", "parameters"],
    commonMistakes: ["Thinking LLMs 'know facts' like a database"],
    masteryCriteria: "You can explain to a peer why an LLM hallucinates.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: [],
    skillIds: ["skill-llm-fundamentals"],
    unitIds: ["unit-llm-what-are-01", "unit-llm-what-are-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-llm-tokens-context",
    categoryId: "category-llm-fundamentals",
    order: 2,
    title: "Tokens, Context Windows & Limits",
    slug: "tokens-context-limits",
    shortDescription: "Tokenization, context windows, why length/cost matter and truncation effects.",
    whyItMatters: "Tokens drive cost, latency and what fits in a prompt.",
    learningObjectives: ["Count tokens", "Reason about context limits and cost"],
    concepts: ["tokens", "tokenizer", "context window", "truncation", "cost-per-token"],
    commonMistakes: ["Assuming words = tokens", "Ignoring context overflow"],
    masteryCriteria: "You estimate token count/cost for a prompt and trim it to fit.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-what-are"],
    skillIds: ["skill-llm-fundamentals", "skill-tokenization"],
    unitIds: ["unit-llm-tokens-context-01", "unit-llm-tokens-context-02", "unit-llm-tokens-context-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-llm-capabilities-limits",
    categoryId: "category-llm-fundamentals",
    order: 3,
    title: "Capabilities, Hallucination & Failure Modes",
    slug: "capabilities-limits",
    shortDescription: "What LLMs do well/badly, hallucination, non-determinism and knowledge cutoff.",
    whyItMatters: "Knowing failure modes tells you when not to use an LLM.",
    learningObjectives: ["Anticipate failure modes", "Know when not to use an LLM"],
    concepts: ["hallucination", "determinism/temperature", "knowledge cutoff", "bias"],
    commonMistakes: ["Trusting outputs as ground truth"],
    masteryCriteria: "You can predict where a given task will fail and why.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-what-are"],
    skillIds: ["skill-llm-fundamentals"],
    unitIds: ["unit-llm-capabilities-limits-01", "unit-llm-capabilities-limits-02", "unit-llm-capabilities-limits-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-llm-landscape",
    categoryId: "category-llm-fundamentals",
    order: 4,
    title: "Model Landscape & Selection",
    slug: "model-landscape",
    shortDescription: "Proprietary vs open models, major families, and how to choose one.",
    whyItMatters: "Choosing the right model controls cost, quality and latency.",
    learningObjectives: ["Compare models on cost/quality/latency/licensing", "Pick a model for a task"],
    concepts: ["model families", "hosted vs self-host", "licensing", "benchmarks (with skepticism)"],
    commonMistakes: ["Always defaulting to the biggest/most expensive model"],
    masteryCriteria: "You can justify a model choice for a use case and budget.",
    difficulty: "beginner",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-capabilities-limits"],
    skillIds: ["skill-llm-fundamentals", "skill-model-selection"],
    unitIds: ["unit-llm-landscape-01", "unit-llm-landscape-02", "unit-llm-landscape-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-llm-inference-params",
    categoryId: "category-llm-fundamentals",
    order: 5,
    title: "Inference Parameters",
    slug: "inference-parameters",
    shortDescription: "Temperature, top-p, max tokens, stop sequences and seeds — and their effects.",
    whyItMatters: "Parameters decide whether output is reproducible or creative.",
    learningObjectives: ["Tune sampling parameters", "Make output deterministic or diverse"],
    concepts: ["temperature", "top-p", "max_tokens", "stop", "penalties"],
    commonMistakes: ["High temperature for factual tasks"],
    masteryCriteria: "You can dial in params to make output reproducible or diverse on demand.",
    difficulty: "beginner",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-tokens-context"],
    skillIds: ["skill-llm-fundamentals"],
    unitIds: ["unit-llm-inference-params-01", "unit-llm-inference-params-02", "unit-llm-inference-params-03"],
    relatedProjectIds: [],
  },

  // ── Category 3 · LLM APIs & Prompt Engineering ──────────────────────────────
  {
    id: "topic-api-first-call",
    categoryId: "category-llm-apis",
    order: 1,
    title: "Your First LLM API Call",
    slug: "first-llm-api-call",
    shortDescription: "Chat completions, message roles and reading responses (OpenAI-compatible + Azure OpenAI).",
    whyItMatters: "This is the foundational call every AI feature builds on.",
    learningObjectives: ["Authenticate and send chat messages", "Parse responses on OpenAI and Azure OpenAI"],
    concepts: ["chat API", "system/user/assistant roles", "usage/cost", "Azure deployment names"],
    commonMistakes: ["Leaking keys", "Ignoring usage/cost", "Hardcoding endpoints"],
    masteryCriteria: "You run the same logic against OpenAI and Azure OpenAI.",
    difficulty: "beginner",
    estimatedHours: 6,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-py-async-http", "topic-llm-inference-params"],
    skillIds: ["skill-llm-apis", "skill-azure-ai"],
    unitIds: ["unit-api-first-call-01", "unit-api-first-call-02", "unit-api-first-call-03", "unit-api-first-call-04"],
    relatedProjectIds: ["project-p1-structured-output"],
  },
  {
    id: "topic-api-prompting-core",
    categoryId: "category-llm-apis",
    order: 2,
    title: "Prompt Engineering Foundations",
    slug: "prompt-engineering-foundations",
    shortDescription: "System prompts, instructions, few-shot, roles, delimiters and iterative refinement.",
    whyItMatters: "Prompting is the primary way to steer model behavior reliably.",
    learningObjectives: ["Write reliable prompts", "Use few-shot and delimiters", "Iterate methodically"],
    concepts: ["system prompt", "few-shot", "delimiters", "instruction clarity", "prompt iteration"],
    commonMistakes: ["Vague prompts", "Overstuffing", "No examples where needed"],
    masteryCriteria: "You turn a flaky prompt into a consistent one via systematic edits.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-api-first-call"],
    skillIds: ["skill-prompt-engineering"],
    unitIds: ["unit-api-prompting-core-01", "unit-api-prompting-core-02", "unit-api-prompting-core-03", "unit-api-prompting-core-04"],
    relatedProjectIds: ["project-p1-structured-output"],
  },
  {
    id: "topic-api-reasoning-patterns",
    categoryId: "category-llm-apis",
    order: 3,
    title: "Reasoning & Prompt Patterns",
    slug: "reasoning-prompt-patterns",
    shortDescription: "Chain-of-thought, step-by-step, self-critique and decomposition — when they help or hurt.",
    whyItMatters: "The right pattern fixes reasoning failures without wasting tokens.",
    learningObjectives: ["Apply reasoning patterns appropriately", "Know their cost"],
    concepts: ["chain-of-thought", "decomposition", "self-critique", "reflection prompting"],
    commonMistakes: ["Using CoT everywhere", "Over-engineering simple tasks"],
    masteryCriteria: "You choose the minimal pattern that fixes a reasoning failure.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-api-prompting-core"],
    skillIds: ["skill-prompt-engineering"],
    unitIds: ["unit-api-reasoning-patterns-01", "unit-api-reasoning-patterns-02", "unit-api-reasoning-patterns-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-api-structured-output",
    categoryId: "category-llm-apis",
    order: 4,
    title: "Structured Output & Function/Tool Calling Basics",
    slug: "structured-output-basics",
    shortDescription: "Reliable JSON, JSON mode/schemas, structured outputs and an intro to tool/function calling.",
    whyItMatters: "Structured output is the backbone of extraction, tools and agents.",
    learningObjectives: ["Enforce JSON schemas", "Validate outputs", "Do basic function calling"],
    concepts: ["JSON mode", "schema/structured outputs", "function/tool calling", "validation (pydantic)"],
    commonMistakes: ["Parsing free text with regex instead of schemas", "No validation"],
    masteryCriteria: "You get schema-valid JSON out of the model every time.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-api-prompting-core", "topic-py-data-structures"],
    skillIds: ["skill-structured-outputs"],
    unitIds: ["unit-api-structured-output-01", "unit-api-structured-output-02", "unit-api-structured-output-03", "unit-api-structured-output-04"],
    relatedProjectIds: ["project-p1-structured-output"],
  },
  {
    id: "topic-api-streaming-robustness",
    categoryId: "category-llm-apis",
    order: 5,
    title: "Streaming, Errors, Retries & Cost Control",
    slug: "streaming-robustness",
    shortDescription: "Token streaming, rate-limit/error handling, retries/backoff, caching and cost/latency tracking.",
    whyItMatters: "Production API usage must survive failures and stay on budget.",
    learningObjectives: ["Stream responses", "Handle failures gracefully", "Control cost"],
    concepts: ["streaming", "rate limits", "exponential backoff", "caching", "usage tracking"],
    commonMistakes: ["No retry/backoff", "Unbounded cost", "Blocking UI on full response"],
    masteryCriteria: "You build a production-grade wrapper with streaming, resilience and cost logging.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-api-first-call", "topic-py-errors-logging"],
    skillIds: ["skill-resilience", "skill-llm-apis"],
    unitIds: ["unit-api-streaming-robustness-01", "unit-api-streaming-robustness-02", "unit-api-streaming-robustness-03", "unit-api-streaming-robustness-04"],
    relatedProjectIds: ["project-p1-structured-output"],
  },
  {
    id: "topic-api-conversation-state",
    categoryId: "category-llm-apis",
    order: 6,
    title: "Conversation State & Memory Basics",
    slug: "conversation-state",
    shortDescription: "Managing multi-turn context, history truncation/summarization and persona persistence.",
    whyItMatters: "Coherent multi-turn conversations must fit within context limits.",
    learningObjectives: ["Maintain coherent multi-turn conversations", "Summarize history to fit the window"],
    concepts: ["message history", "truncation", "rolling summary", "memory windows"],
    commonMistakes: ["Unbounded history overflow", "Losing the system prompt"],
    masteryCriteria: "You build a chat loop that stays coherent past the context window via summarization.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-api-first-call", "topic-llm-tokens-context"],
    skillIds: ["skill-tokenization", "skill-llm-apis"],
    unitIds: ["unit-api-conversation-state-01", "unit-api-conversation-state-02", "unit-api-conversation-state-03"],
    relatedProjectIds: ["project-p1-structured-output"],
  },

  // ── Category 4 · Embeddings & Semantic Search ───────────────────────────────
  {
    id: "topic-emb-concepts",
    categoryId: "category-embeddings",
    order: 1,
    title: "What Embeddings Represent",
    slug: "embedding-concepts",
    shortDescription: "Vectors, semantic similarity, dimensions and distance metrics (cosine/dot/euclidean).",
    whyItMatters: "Embeddings are the foundation of retrieval and RAG.",
    learningObjectives: ["Explain embedding space", "Choose a distance metric"],
    concepts: ["vector space", "cosine similarity", "dimensionality", "distance metrics"],
    commonMistakes: ["Confusing cosine vs euclidean", "Ignoring normalization"],
    masteryCriteria: "You can explain why two sentences are close in embedding space.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-inference-params"],
    skillIds: ["skill-embeddings"],
    unitIds: ["unit-emb-concepts-01", "unit-emb-concepts-02"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-emb-generate",
    categoryId: "category-embeddings",
    order: 2,
    title: "Generating Embeddings",
    slug: "generating-embeddings",
    shortDescription: "Embedding APIs (OpenAI/Azure) and local models, batching and normalization.",
    whyItMatters: "You must produce and store embeddings efficiently to build retrieval.",
    learningObjectives: ["Produce embeddings via API and locally", "Batch efficiently"],
    concepts: ["embedding models", "batching", "normalization", "dimensions/cost"],
    commonMistakes: ["Re-embedding unchanged text", "Mismatched model dimensions"],
    masteryCriteria: "You embed a corpus efficiently and store the vectors.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-emb-concepts", "topic-api-first-call"],
    skillIds: ["skill-embeddings"],
    unitIds: ["unit-emb-generate-01", "unit-emb-generate-02", "unit-emb-generate-03"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-emb-similarity",
    categoryId: "category-embeddings",
    order: 3,
    title: "Similarity & Semantic Comparison",
    slug: "similarity-comparison",
    shortDescription: "Compute similarity, rank results, set thresholds and find nearest neighbors.",
    whyItMatters: "Ranking by similarity is the core retrieval operation.",
    learningObjectives: ["Rank texts by similarity", "Set sensible thresholds"],
    concepts: ["cosine similarity", "top-k", "thresholds", "brute-force kNN"],
    commonMistakes: ["Arbitrary thresholds", "Forgetting normalization"],
    masteryCriteria: "Given a query, you return the most semantically relevant items.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-emb-generate"],
    skillIds: ["skill-embeddings", "skill-semantic-search"],
    unitIds: ["unit-emb-similarity-01", "unit-emb-similarity-02", "unit-emb-similarity-03", "unit-emb-similarity-04"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-emb-chunking",
    categoryId: "category-embeddings",
    order: 4,
    title: "Chunking & Text Preparation",
    slug: "chunking-text-prep",
    shortDescription: "Splitting documents, chunk size/overlap, structure-aware chunking and metadata.",
    whyItMatters: "Chunking quality directly changes retrieval quality.",
    learningObjectives: ["Chunk documents well for retrieval", "Attach metadata"],
    concepts: ["fixed/recursive/semantic chunking", "overlap", "metadata", "tradeoffs"],
    commonMistakes: ["Chunks too big/small", "Splitting mid-sentence", "No metadata"],
    masteryCriteria: "You choose chunking that measurably improves retrieval.",
    difficulty: "intermediate",
    estimatedHours: 6,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-emb-generate"],
    skillIds: ["skill-chunking", "skill-data-handling"],
    unitIds: ["unit-emb-chunking-01", "unit-emb-chunking-02", "unit-emb-chunking-03", "unit-emb-chunking-04"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-emb-semantic-search-project",
    categoryId: "category-embeddings",
    order: 5,
    title: "Semantic Search System",
    slug: "semantic-search-system",
    shortDescription: "End-to-end small semantic search app that ties the category together and produces the P2 core.",
    whyItMatters: "It integrates ingestion, chunking, embeddings and ranking into a working tool.",
    learningObjectives: ["Ingest → chunk → embed → search over real documents", "Produce the semantic-search core for Project P2"],
    concepts: ["ingestion pipeline", "top-k retrieval", "ranking", "evaluation-by-eye"],
    commonMistakes: ["No evaluation of result quality", "Ignoring metadata filtering"],
    masteryCriteria: "You build a working search tool you would actually use on your own notes/docs.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-emb-similarity", "topic-emb-chunking"],
    skillIds: ["skill-semantic-search", "skill-embeddings", "skill-chunking"],
    unitIds: ["unit-emb-semantic-search-project-01", "unit-emb-semantic-search-project-02", "unit-emb-semantic-search-project-03"],
    relatedProjectIds: ["project-p2-semantic-search"],
    producesArtifact: "semantic-search-core",
  },

  // ── Category 5 · Vector Databases ───────────────────────────────────────────
  {
    id: "topic-vdb-concepts",
    categoryId: "category-vector-databases",
    order: 1,
    title: "Why Vector Databases",
    slug: "why-vector-databases",
    shortDescription: "ANN vs brute force, indexes (HNSW/IVF conceptually) and when you actually need a vector DB.",
    whyItMatters: "Choosing infrastructure correctly avoids premature complexity.",
    learningObjectives: ["Explain ANN tradeoffs", "Know when in-memory is enough"],
    concepts: ["ANN", "HNSW/IVF (conceptual)", "recall vs latency"],
    commonMistakes: ["Reaching for a vector DB when a list would do"],
    masteryCriteria: "You can justify vector-DB adoption for a scale/latency requirement.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-emb-similarity"],
    skillIds: ["skill-vector-databases"],
    unitIds: ["unit-vdb-concepts-01", "unit-vdb-concepts-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-vdb-hands-on",
    categoryId: "category-vector-databases",
    order: 2,
    title: "Using a Vector Database",
    slug: "using-a-vector-database",
    shortDescription: "CRUD with a vector DB (Qdrant/Chroma/pgvector): collections, upserts and queries.",
    whyItMatters: "Real retrieval needs persistent, queryable vector storage.",
    learningObjectives: ["Create collections", "Upsert vectors + metadata", "Query top-k"],
    concepts: ["collections", "upsert", "top-k query", "persistence"],
    commonMistakes: ["Dimension mismatches", "No persistence", "Re-embedding every run"],
    masteryCriteria: "You migrate your in-memory search onto a real vector DB.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-vdb-concepts", "topic-emb-generate"],
    skillIds: ["skill-vector-databases"],
    unitIds: ["unit-vdb-hands-on-01", "unit-vdb-hands-on-02", "unit-vdb-hands-on-03", "unit-vdb-hands-on-04"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-vdb-metadata-hybrid",
    categoryId: "category-vector-databases",
    order: 3,
    title: "Metadata Filtering & Hybrid Search",
    slug: "metadata-hybrid-search",
    shortDescription: "Filtering by metadata, combining keyword + vector (hybrid) and an intro to reranking.",
    whyItMatters: "Hybrid search and filtering beat vector-only on many real datasets.",
    learningObjectives: ["Filter by metadata", "Implement hybrid search", "Understand reranking"],
    concepts: ["metadata filters", "BM25/keyword + vector fusion", "rerankers"],
    commonMistakes: ["Vector-only where keywords matter", "No filtering"],
    masteryCriteria: "You build hybrid retrieval that beats vector-only on your dataset.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-vdb-hands-on"],
    skillIds: ["skill-hybrid-search", "skill-vector-databases"],
    unitIds: ["unit-vdb-metadata-hybrid-01", "unit-vdb-metadata-hybrid-02", "unit-vdb-metadata-hybrid-03", "unit-vdb-metadata-hybrid-04"],
    relatedProjectIds: ["project-p2-semantic-search"],
  },
  {
    id: "topic-vdb-azure-search",
    categoryId: "category-vector-databases",
    order: 4,
    title: "Azure AI Search for Retrieval",
    slug: "azure-ai-search",
    shortDescription: "Azure AI Search as an enterprise retrieval/vector store: index design and integrated vectorization.",
    whyItMatters: "Enterprise retrieval often runs on Azure AI Search; concepts stay transferable.",
    learningObjectives: ["Build an index in Azure AI Search", "Query vectors + filters"],
    concepts: ["indexes", "indexers", "vector + semantic search", "integrated vectorization"],
    commonMistakes: ["Treating it as only keyword search", "Ignoring cost/tiers"],
    masteryCriteria: "You stand up an Azure AI Search index feeding a retrieval app.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-vdb-hands-on"],
    skillIds: ["skill-azure-ai", "skill-vector-databases"],
    unitIds: ["unit-vdb-azure-search-01", "unit-vdb-azure-search-02", "unit-vdb-azure-search-03"],
    relatedProjectIds: ["project-p2-semantic-search", "project-p3-rag-app"],
  },

  // ── Category 6 · RAG ────────────────────────────────────────────────────────
  {
    id: "topic-rag-concepts",
    categoryId: "category-rag",
    order: 1,
    title: "RAG Fundamentals",
    slug: "rag-fundamentals",
    shortDescription: "Retrieve→augment→generate, why RAG, and when to use it vs fine-tune vs long-context.",
    whyItMatters: "Choosing RAG vs alternatives is a core architecture decision.",
    learningObjectives: ["Explain the RAG loop", "Choose RAG vs alternatives"],
    concepts: ["retrieval", "context injection", "grounding", "RAG vs fine-tune vs long-context"],
    commonMistakes: ["Using RAG where a prompt/long-context suffices"],
    masteryCriteria: "You can justify RAG for a use case and sketch the pipeline.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-emb-similarity", "topic-vdb-hands-on"],
    skillIds: ["skill-rag"],
    unitIds: ["unit-rag-concepts-01", "unit-rag-concepts-02"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-rag-basic-pipeline",
    categoryId: "category-rag",
    order: 2,
    title: "Building a Basic RAG Pipeline",
    slug: "basic-rag-pipeline",
    shortDescription: "Ingest→chunk→embed→store→retrieve→prompt→answer with citations.",
    whyItMatters: "This end-to-end pipeline is the canonical AI-engineering deliverable.",
    learningObjectives: ["Build an end-to-end RAG app", "Add source citations"],
    concepts: ["ingestion pipeline", "context assembly", "prompt grounding", "citations"],
    commonMistakes: ["Dumping raw chunks", "No citations", "Context overflow"],
    masteryCriteria: "You build a RAG app that answers from your docs and cites sources.",
    difficulty: "intermediate",
    estimatedHours: 9,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-concepts", "topic-emb-chunking", "topic-vdb-hands-on"],
    skillIds: ["skill-rag"],
    unitIds: ["unit-rag-basic-pipeline-01", "unit-rag-basic-pipeline-02", "unit-rag-basic-pipeline-03", "unit-rag-basic-pipeline-04"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-rag-quality",
    categoryId: "category-rag",
    order: 3,
    title: "Improving Retrieval Quality",
    slug: "improving-retrieval-quality",
    shortDescription: "Reranking, query rewriting/expansion, hybrid retrieval and metadata filtering in RAG.",
    whyItMatters: "Most RAG failures are retrieval failures, not generation failures.",
    learningObjectives: ["Measurably improve retrieval relevance", "Diagnose retrieval vs generation issues"],
    concepts: ["reranking", "query rewriting", "HyDE", "hybrid", "filtering"],
    commonMistakes: ["Tuning the prompt while retrieval is the real problem"],
    masteryCriteria: "You diagnose whether failures are retrieval or generation, and fix retrieval.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-basic-pipeline", "topic-vdb-metadata-hybrid"],
    skillIds: ["skill-retrieval-quality", "skill-hybrid-search"],
    unitIds: ["unit-rag-quality-01", "unit-rag-quality-02", "unit-rag-quality-03", "unit-rag-quality-04"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-rag-evaluation",
    categoryId: "category-rag",
    order: 4,
    title: "Evaluating RAG",
    slug: "evaluating-rag",
    shortDescription: "Faithfulness, relevance and groundedness; RAG eval frameworks and test sets.",
    whyItMatters: "Shipping RAG without evaluation guarantees silent regressions.",
    learningObjectives: ["Build an eval harness", "Measure faithfulness/relevance"],
    concepts: ["faithfulness", "answer/context relevance", "eval datasets", "LLM-as-judge"],
    commonMistakes: ["Shipping RAG with zero evaluation"],
    masteryCriteria: "You have a repeatable eval that catches regressions.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-basic-pipeline"],
    skillIds: ["skill-evaluation", "skill-rag"],
    unitIds: ["unit-rag-evaluation-01", "unit-rag-evaluation-02", "unit-rag-evaluation-03", "unit-rag-evaluation-04"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-rag-advanced-patterns",
    categoryId: "category-rag",
    order: 5,
    title: "Advanced RAG Patterns",
    slug: "advanced-rag-patterns",
    shortDescription: "Multi-hop, parent/child, contextual retrieval, agentic RAG intro and graph RAG (light).",
    whyItMatters: "Advanced patterns fix real gaps once basic RAG is solid and evaluated.",
    learningObjectives: ["Apply advanced patterns where basic RAG falls short", "Deliver the P3 RAG application"],
    concepts: ["multi-hop", "hierarchical chunks", "contextual retrieval", "agentic/graph RAG"],
    commonMistakes: ["Adding complexity before basic RAG is solid/evaluated"],
    masteryCriteria: "You pick the minimal advanced pattern that fixes a real gap.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-quality"],
    skillIds: ["skill-rag", "skill-retrieval-quality"],
    unitIds: ["unit-rag-advanced-patterns-01", "unit-rag-advanced-patterns-02", "unit-rag-advanced-patterns-03", "unit-rag-advanced-patterns-04"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
];
