import type { Topic } from "./types";

// Topics for categories 7–15. Locked ordering preserved. recommendedAfter is
// ADVISORY only. topic.track carries the CONTENT classification (core/useful/
// optional-depth); category.track governs primary-progress weighting.
export const topicsPartB: Topic[] = [
  // ── Category 7 · Orchestration ──────────────────────────────────────────────
  {
    id: "topic-orch-why",
    categoryId: "category-orchestration",
    order: 1,
    title: "Why (and When Not To) Use Frameworks",
    slug: "why-frameworks",
    shortDescription: "What orchestration frameworks provide, their abstraction cost and build-vs-framework tradeoffs.",
    whyItMatters: "Frameworks accelerate work but can hide too much if adopted blindly.",
    learningObjectives: ["Decide when a framework helps vs hides too much"],
    concepts: ["abstractions", "chains/graphs", "lock-in", "debuggability"],
    commonMistakes: ["Framework-first before understanding raw calls"],
    masteryCriteria: "You can articulate framework tradeoffs for a given project.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-basic-pipeline"],
    skillIds: ["skill-orchestration"],
    unitIds: ["unit-orch-why-01", "unit-orch-why-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-orch-langchain",
    categoryId: "category-orchestration",
    order: 2,
    title: "LangChain Essentials",
    slug: "langchain-essentials",
    shortDescription: "Core abstractions, LCEL/composition, chains, memory, retrievers and tools.",
    whyItMatters: "LangChain is a common way to compose LLM apps quickly.",
    learningObjectives: ["Rebuild RAG using LangChain idioms", "Explain each component"],
    concepts: ["chains/LCEL", "retrievers", "memory", "tools", "callbacks"],
    commonMistakes: ["Cargo-culting chains", "Not inspecting intermediate steps"],
    masteryCriteria: "You implement RAG in LangChain and explain every component.",
    difficulty: "intermediate",
    estimatedHours: 10,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-orch-why"],
    skillIds: ["skill-orchestration", "skill-rag"],
    unitIds: ["unit-orch-langchain-01", "unit-orch-langchain-02", "unit-orch-langchain-03", "unit-orch-langchain-04"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-orch-llamaindex",
    categoryId: "category-orchestration",
    order: 3,
    title: "LlamaIndex for Data-Centric RAG",
    slug: "llamaindex-data-rag",
    shortDescription: "Data connectors, indices, query engines and node post-processors.",
    whyItMatters: "LlamaIndex excels at data-centric ingestion and querying.",
    learningObjectives: ["Build ingestion + query with LlamaIndex", "Contrast with LangChain"],
    concepts: ["documents/nodes", "indices", "query engines", "postprocessors"],
    commonMistakes: ["Duplicating pipelines across frameworks needlessly"],
    masteryCriteria: "You can choose the right framework per task.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-orch-why"],
    skillIds: ["skill-orchestration", "skill-rag"],
    unitIds: ["unit-orch-llamaindex-01", "unit-orch-llamaindex-02", "unit-orch-llamaindex-03"],
    relatedProjectIds: ["project-p3-rag-app"],
  },
  {
    id: "topic-orch-langgraph",
    categoryId: "category-orchestration",
    order: 4,
    title: "Stateful Orchestration (LangGraph)",
    slug: "langgraph-stateful",
    shortDescription: "Graph-based, stateful, controllable flows — a bridge to agents.",
    whyItMatters: "Explicit state and control matter as flows become multi-step.",
    learningObjectives: ["Model a multi-step app as a state graph"],
    concepts: ["nodes/edges", "state", "branching", "human-in-the-loop"],
    commonMistakes: ["Graphs for trivially linear flows"],
    masteryCriteria: "You build a controllable multi-step flow with explicit state.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-orch-langchain"],
    skillIds: ["skill-orchestration", "skill-agents"],
    unitIds: ["unit-orch-langgraph-01", "unit-orch-langgraph-02", "unit-orch-langgraph-03"],
    relatedProjectIds: ["project-p4-agent"],
  },

  // ── Category 8 · AI Agents & Tool Use ───────────────────────────────────────
  {
    id: "topic-agent-concepts",
    categoryId: "category-agents",
    order: 1,
    title: "What Agents Are",
    slug: "what-agents-are",
    shortDescription: "The agent loop (reason→act→observe), the autonomy spectrum and when agents beat pipelines.",
    whyItMatters: "Agents are powerful but often the wrong, costlier tool.",
    learningObjectives: ["Explain the agent loop", "Know when NOT to use agents"],
    concepts: ["ReAct loop", "autonomy", "planning", "tools", "termination"],
    commonMistakes: ["Using an agent where a deterministic pipeline is better/cheaper"],
    masteryCriteria: "You can decide agent-vs-pipeline for a task.",
    difficulty: "advanced",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-api-structured-output", "topic-orch-langgraph"],
    skillIds: ["skill-agents"],
    unitIds: ["unit-agent-concepts-01", "unit-agent-concepts-02"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-agent-tool-calling",
    categoryId: "category-agents",
    order: 2,
    title: "Tool / Function Calling in Depth",
    slug: "tool-function-calling",
    shortDescription: "Defining tools/schemas, argument validation, execution, feeding results back and error handling.",
    whyItMatters: "Reliable tool calling is the heart of a useful agent.",
    learningObjectives: ["Build robust tools the model can call reliably", "Handle bad args and failures"],
    concepts: ["tool schemas", "arg validation", "execution loop", "error/timeout handling"],
    commonMistakes: ["Unvalidated args", "No error recovery", "Unsafe tool execution"],
    masteryCriteria: "You build a tool-calling loop that handles bad args and failures gracefully.",
    difficulty: "advanced",
    estimatedHours: 10,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-agent-concepts", "topic-api-structured-output"],
    skillIds: ["skill-tool-calling", "skill-structured-outputs"],
    unitIds: ["unit-agent-tool-calling-01", "unit-agent-tool-calling-02", "unit-agent-tool-calling-03", "unit-agent-tool-calling-04"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-agent-memory-planning",
    categoryId: "category-agents",
    order: 3,
    title: "Agent Memory, Planning & Multi-step",
    slug: "agent-memory-planning",
    shortDescription: "Short/long-term memory, planning/decomposition, reflection and loop control/termination.",
    whyItMatters: "Bounded multi-step planning is what makes agents dependable.",
    learningObjectives: ["Give agents memory and bounded multi-step planning"],
    concepts: ["working/long-term memory", "planning", "reflection", "step limits"],
    commonMistakes: ["Infinite loops", "Unbounded cost", "No termination criteria"],
    masteryCriteria: "You build a multi-step agent that reliably terminates and stays on budget.",
    difficulty: "advanced",
    estimatedHours: 10,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-agent-tool-calling"],
    skillIds: ["skill-agents", "skill-tool-calling"],
    unitIds: ["unit-agent-memory-planning-01", "unit-agent-memory-planning-02", "unit-agent-memory-planning-03", "unit-agent-memory-planning-04"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-agent-frameworks-protocols",
    categoryId: "category-agents",
    order: 4,
    title: "Agent Frameworks & Standards (MCP)",
    slug: "agent-frameworks-mcp",
    shortDescription: "LangGraph agents, the framework landscape and the Model Context Protocol for tools.",
    whyItMatters: "Standard protocols avoid reinventing tool interfaces and lock-in.",
    learningObjectives: ["Build with an agent framework", "Expose/consume tools via MCP"],
    concepts: ["agent frameworks", "MCP", "tool servers", "interoperability"],
    commonMistakes: ["Vendor/framework lock-in", "Reinventing tool protocols"],
    masteryCriteria: "You connect an agent to tools via a standard protocol.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-agent-tool-calling"],
    skillIds: ["skill-mcp", "skill-tool-calling"],
    unitIds: ["unit-agent-frameworks-protocols-01", "unit-agent-frameworks-protocols-02", "unit-agent-frameworks-protocols-03"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-agent-multiagent",
    categoryId: "category-agents",
    order: 5,
    title: "Multi-Agent & Orchestrated Systems",
    slug: "multi-agent-systems",
    shortDescription: "Multiple cooperating agents, roles, orchestration and handoffs — and their real cost.",
    whyItMatters: "Multi-agent is often theater; you must judge its ROI critically.",
    learningObjectives: ["Evaluate whether multi-agent is worth it", "Build a minimal example", "Deliver Project P4"],
    concepts: ["roles", "orchestrator/worker", "handoffs", "communication overhead"],
    commonMistakes: ["Multi-agent theater where one agent suffices"],
    masteryCriteria: "You can critically judge multi-agent ROI against a single-agent baseline.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-agent-memory-planning"],
    skillIds: ["skill-agents"],
    unitIds: ["unit-agent-multiagent-01", "unit-agent-multiagent-02", "unit-agent-multiagent-03", "unit-agent-multiagent-04"],
    relatedProjectIds: ["project-p4-agent"],
  },

  // ── Category 9 · Multimodal AI ──────────────────────────────────────────────
  {
    id: "topic-mm-vision",
    categoryId: "category-multimodal",
    order: 1,
    title: "Vision & Image Understanding",
    slug: "vision-image-understanding",
    shortDescription: "Vision-capable LLMs, image inputs, OCR/document understanding and structured extraction from images.",
    whyItMatters: "Document/image understanding unlocks a huge class of real features.",
    learningObjectives: ["Send images to a model", "Extract structured data from documents/images"],
    concepts: ["vision models", "image inputs", "OCR", "doc understanding"],
    commonMistakes: ["Huge images/cost", "Assuming perfect OCR"],
    masteryCriteria: "You extract structured fields from an invoice/screenshot reliably.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-api-structured-output"],
    skillIds: ["skill-multimodal", "skill-structured-outputs"],
    unitIds: ["unit-mm-vision-01", "unit-mm-vision-02", "unit-mm-vision-03", "unit-mm-vision-04"],
    relatedProjectIds: ["project-p5-multimodal"],
  },
  {
    id: "topic-mm-speech-audio",
    categoryId: "category-multimodal",
    order: 2,
    title: "Speech & Audio (STT/TTS)",
    slug: "speech-audio",
    shortDescription: "Speech-to-text, text-to-speech and transcription pipelines (Whisper, Azure Speech).",
    whyItMatters: "Voice interfaces and transcription are common product requirements.",
    learningObjectives: ["Transcribe audio", "Synthesize speech in an app"],
    concepts: ["STT", "TTS", "diarization (light)", "streaming audio"],
    commonMistakes: ["Ignoring latency/format", "No error handling on long audio"],
    masteryCriteria: "You build a voice pipeline: audio in → text → LLM → speech out.",
    difficulty: "intermediate",
    estimatedHours: 6,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-api-first-call"],
    skillIds: ["skill-multimodal"],
    unitIds: ["unit-mm-speech-audio-01", "unit-mm-speech-audio-02", "unit-mm-speech-audio-03"],
    relatedProjectIds: ["project-p5-multimodal"],
  },
  {
    id: "topic-mm-image-gen",
    categoryId: "category-multimodal",
    order: 3,
    title: "Image Generation",
    slug: "image-generation",
    shortDescription: "Text-to-image APIs, prompting for images, editing/variations and practical uses.",
    whyItMatters: "Programmatic image generation powers many product features.",
    learningObjectives: ["Generate/edit images programmatically", "Add content safety"],
    concepts: ["text-to-image", "image editing", "prompt control", "safety"],
    commonMistakes: ["Ignoring content safety", "Unbounded generation cost"],
    masteryCriteria: "You integrate image generation into an app feature with safety checks.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-api-first-call"],
    skillIds: ["skill-multimodal"],
    unitIds: ["unit-mm-image-gen-01", "unit-mm-image-gen-02", "unit-mm-image-gen-03"],
    relatedProjectIds: ["project-p5-multimodal"],
  },
  {
    id: "topic-mm-multimodal-rag",
    categoryId: "category-multimodal",
    order: 4,
    title: "Multimodal RAG",
    slug: "multimodal-rag",
    shortDescription: "Retrieval over documents with images/tables, multimodal embeddings and PDF-with-figures Q&A.",
    whyItMatters: "Real documents contain figures and tables that text-only RAG drops.",
    learningObjectives: ["Build RAG that handles images/tables", "Deliver Project P5"],
    concepts: ["multimodal embeddings", "image+text retrieval", "table/figure handling"],
    commonMistakes: ["Dropping non-text content silently"],
    masteryCriteria: "You answer questions grounded in the figures/tables of a PDF.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-mm-vision", "topic-rag-basic-pipeline"],
    skillIds: ["skill-multimodal", "skill-rag"],
    unitIds: ["unit-mm-multimodal-rag-01", "unit-mm-multimodal-rag-02", "unit-mm-multimodal-rag-03", "unit-mm-multimodal-rag-04"],
    relatedProjectIds: ["project-p5-multimodal"],
  },

  // ── Category 10 · Open-Source Models & Hugging Face ─────────────────────────
  {
    id: "topic-oss-huggingface",
    categoryId: "category-open-models",
    order: 1,
    title: "Hugging Face Ecosystem",
    slug: "huggingface-ecosystem",
    shortDescription: "Hub, models/datasets, transformers basics, pipelines and model cards.",
    whyItMatters: "The HF ecosystem is the gateway to open models.",
    learningObjectives: ["Find/load models", "Run inference via pipelines", "Read model cards"],
    concepts: ["Hub", "transformers", "pipelines", "tokenizers", "model cards/licenses"],
    commonMistakes: ["Ignoring licenses", "Loading huge models without checking resources"],
    masteryCriteria: "You run inference with an open model locally via pipelines.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-py-data-libs", "topic-llm-what-are"],
    skillIds: ["skill-open-models"],
    unitIds: ["unit-oss-huggingface-01", "unit-oss-huggingface-02", "unit-oss-huggingface-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-oss-local-inference",
    categoryId: "category-open-models",
    order: 2,
    title: "Running Models Locally",
    slug: "local-inference",
    shortDescription: "Ollama / llama.cpp / LM Studio, quantization, GGUF and hardware limits.",
    whyItMatters: "Local models give cost, privacy and offline control.",
    learningObjectives: ["Run a quantized LLM locally", "Call it from code"],
    concepts: ["quantization", "GGUF", "local runtimes", "VRAM/RAM tradeoffs"],
    commonMistakes: ["Expecting frontier quality", "Wrong quant for hardware"],
    masteryCriteria: "You run a local model and hit it from a Python app.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-oss-huggingface"],
    skillIds: ["skill-open-models"],
    unitIds: ["unit-oss-local-inference-01", "unit-oss-local-inference-02", "unit-oss-local-inference-03", "unit-oss-local-inference-04"],
    relatedProjectIds: [],
  },
  {
    id: "topic-oss-serving",
    categoryId: "category-open-models",
    order: 3,
    title: "Serving Open Models (OpenAI-Compatible)",
    slug: "serving-open-models",
    shortDescription: "vLLM/TGI, OpenAI-compatible endpoints and batching/throughput basics.",
    whyItMatters: "One interface for hosted and self-hosted models keeps apps portable.",
    learningObjectives: ["Serve an open model behind an OpenAI-compatible API"],
    concepts: ["vLLM/TGI", "OpenAI-compatible API", "throughput/batching"],
    commonMistakes: ["Ignoring concurrency/throughput", "No health checks"],
    masteryCriteria: "Your app talks to self-hosted and hosted models via one interface.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-oss-local-inference", "topic-api-first-call"],
    skillIds: ["skill-model-serving", "skill-open-models"],
    unitIds: ["unit-oss-serving-01", "unit-oss-serving-02", "unit-oss-serving-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-oss-embeddings-local",
    categoryId: "category-open-models",
    order: 4,
    title: "Local Embeddings & Rerankers",
    slug: "local-embeddings-rerankers",
    shortDescription: "Open embedding models (SBERT/BGE) and cross-encoder rerankers running offline.",
    whyItMatters: "A fully local retrieval stack maximizes privacy and cost control.",
    learningObjectives: ["Replace hosted embeddings/reranker with open models"],
    concepts: ["sentence-transformers", "cross-encoders", "offline retrieval"],
    commonMistakes: ["Dimension/model mismatches when swapping"],
    masteryCriteria: "You run a fully local retrieval stack.",
    difficulty: "intermediate",
    estimatedHours: 6,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-emb-generate", "topic-oss-huggingface"],
    skillIds: ["skill-open-models", "skill-embeddings", "skill-hybrid-search"],
    unitIds: ["unit-oss-embeddings-local-01", "unit-oss-embeddings-local-02", "unit-oss-embeddings-local-03"],
    relatedProjectIds: [],
  },

  // ── Category 11 · Fine-Tuning (optional-depth category) ─────────────────────
  {
    id: "topic-ft-when",
    categoryId: "category-fine-tuning",
    order: 1,
    title: "When to Fine-Tune (vs Prompt/RAG)",
    slug: "when-to-fine-tune",
    shortDescription: "A decision framework: prompt → RAG → fine-tune, and what fine-tuning does/doesn't fix.",
    whyItMatters: "Fine-tuning is often the wrong first tool; knowing when matters most.",
    learningObjectives: ["Correctly decide whether fine-tuning is warranted"],
    concepts: ["capability vs knowledge", "style/format adaptation", "cost/maintenance"],
    commonMistakes: ["Fine-tuning to add knowledge (usually a RAG job)"],
    masteryCriteria: "You reject fine-tuning when RAG/prompting suffices, and accept it when it doesn't.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-basic-pipeline", "topic-api-prompting-core"],
    skillIds: ["skill-fine-tuning"],
    unitIds: ["unit-ft-when-01", "unit-ft-when-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-ft-data",
    categoryId: "category-fine-tuning",
    order: 2,
    title: "Datasets for Fine-Tuning",
    slug: "fine-tuning-datasets",
    shortDescription: "Building instruction/preference datasets, formatting, quality and splits.",
    whyItMatters: "Fine-tune quality is bounded by dataset quality.",
    learningObjectives: ["Create a clean, well-formatted fine-tune dataset"],
    concepts: ["instruction data", "formatting", "quality/dedup", "train/val split"],
    commonMistakes: ["Tiny/dirty datasets", "Data leakage"],
    masteryCriteria: "You produce a validated dataset ready for training.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-ft-when"],
    skillIds: ["skill-fine-tuning", "skill-data-handling"],
    unitIds: ["unit-ft-data-01", "unit-ft-data-02", "unit-ft-data-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-ft-hosted",
    categoryId: "category-fine-tuning",
    order: 3,
    title: "Hosted Fine-Tuning (OpenAI / Azure OpenAI)",
    slug: "hosted-fine-tuning",
    shortDescription: "Fine-tune via managed services, evaluate and deploy — no GPU management.",
    whyItMatters: "Managed fine-tuning is the pragmatic path for most teams.",
    learningObjectives: ["Run and deploy a hosted fine-tune", "Measure improvement"],
    concepts: ["managed fine-tune workflow", "deployment", "eval", "cost"],
    commonMistakes: ["No baseline/eval", "Overfitting to tiny data"],
    masteryCriteria: "You demonstrate a fine-tune beats the base model on your eval.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-ft-data"],
    skillIds: ["skill-fine-tuning", "skill-azure-ai", "skill-evaluation"],
    unitIds: ["unit-ft-hosted-01", "unit-ft-hosted-02", "unit-ft-hosted-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-ft-lora",
    categoryId: "category-fine-tuning",
    order: 4,
    title: "Parameter-Efficient Fine-Tuning (LoRA/QLoRA)",
    slug: "peft-lora",
    shortDescription: "LoRA/QLoRA conceptually plus one practical run on a small open model.",
    whyItMatters: "PEFT makes open-model adaptation feasible on modest hardware.",
    learningObjectives: ["Run a small PEFT fine-tune", "Load and use the adapter"],
    concepts: ["LoRA/QLoRA", "adapters", "PEFT", "resource needs"],
    commonMistakes: ["Chasing full fine-tunes", "Underestimating hardware"],
    masteryCriteria: "You produce and use a LoRA adapter on a small model.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-ft-data", "topic-oss-huggingface"],
    skillIds: ["skill-fine-tuning", "skill-open-models"],
    unitIds: ["unit-ft-lora-01", "unit-ft-lora-02", "unit-ft-lora-03"],
    relatedProjectIds: [],
  },

  // ── Category 12 · Evaluation, Observability & Quality ───────────────────────
  {
    id: "topic-eval-why",
    categoryId: "category-evaluation",
    order: 1,
    title: "Why Evaluation Is Hard",
    slug: "why-evaluation-is-hard",
    shortDescription: "Non-determinism, no single ground truth, and offline vs online evaluation.",
    whyItMatters: "You must frame evaluation correctly before measuring anything.",
    learningObjectives: ["Frame evaluation for generative systems"],
    concepts: ["non-determinism", "reference-free eval", "offline/online"],
    commonMistakes: ["Expecting a single accuracy number"],
    masteryCriteria: "You can design an evaluation strategy for a fuzzy task.",
    difficulty: "intermediate",
    estimatedHours: 4,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-capabilities-limits"],
    skillIds: ["skill-evaluation"],
    unitIds: ["unit-eval-why-01", "unit-eval-why-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-eval-methods",
    categoryId: "category-evaluation",
    order: 2,
    title: "Evaluation Methods & Metrics",
    slug: "evaluation-methods",
    shortDescription: "LLM-as-judge, rubric grading, human eval, task metrics and golden sets.",
    whyItMatters: "Trustworthy scores require validated methods, not vibes.",
    learningObjectives: ["Implement automated + human eval", "Build golden datasets"],
    concepts: ["LLM-as-judge", "rubrics", "pairwise", "golden sets", "bias in judges"],
    commonMistakes: ["Trusting an unvalidated LLM judge blindly"],
    masteryCriteria: "You build an eval whose scores you trust and can defend.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-eval-why", "topic-api-structured-output"],
    skillIds: ["skill-evaluation"],
    unitIds: ["unit-eval-methods-01", "unit-eval-methods-02", "unit-eval-methods-03", "unit-eval-methods-04"],
    relatedProjectIds: [],
  },
  {
    id: "topic-eval-observability",
    categoryId: "category-evaluation",
    order: 3,
    title: "Tracing & Observability",
    slug: "tracing-observability",
    shortDescription: "Tracing LLM calls, prompt/version logging and latency/cost/error dashboards.",
    whyItMatters: "You cannot operate what you cannot observe.",
    learningObjectives: ["Instrument an app for traces, cost, latency and errors"],
    concepts: ["tracing", "spans", "prompt versioning", "monitoring", "feedback capture"],
    commonMistakes: ["No visibility into prod behavior", "No cost tracking"],
    masteryCriteria: "You trace a request end-to-end and spot a regression.",
    difficulty: "intermediate",
    estimatedHours: 9,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "completed"],
    recommendedAfter: ["topic-eval-methods", "topic-api-streaming-robustness"],
    skillIds: ["skill-observability"],
    unitIds: ["unit-eval-observability-01", "unit-eval-observability-02", "unit-eval-observability-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-eval-ci",
    categoryId: "category-evaluation",
    order: 4,
    title: "Evaluation in CI / Regression Testing",
    slug: "evaluation-in-ci",
    shortDescription: "Automated eval gates in CI, regression suites and prompt/version diffing.",
    whyItMatters: "Automated gates stop silent quality regressions from shipping.",
    learningObjectives: ["Block regressions with automated eval gates"],
    concepts: ["eval-in-CI", "thresholds", "regression suites", "drift"],
    commonMistakes: ["Manual eval only", "Shipping silent regressions"],
    masteryCriteria: "You have a CI job that fails on quality regressions.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-eval-methods", "topic-py-env-tooling"],
    skillIds: ["skill-evaluation", "skill-llmops", "skill-git-cicd"],
    unitIds: ["unit-eval-ci-01", "unit-eval-ci-02", "unit-eval-ci-03"],
    relatedProjectIds: [],
  },

  // ── Category 13 · AI Security & Safety ──────────────────────────────────────
  {
    id: "topic-sec-threat-model",
    categoryId: "category-ai-security",
    order: 1,
    title: "LLM Threat Landscape (OWASP LLM Top 10)",
    slug: "llm-threat-landscape",
    shortDescription: "Prompt injection, data leakage, insecure output handling, excessive agency and supply chain.",
    whyItMatters: "LLM apps have a unique attack surface you must be able to enumerate.",
    learningObjectives: ["Enumerate LLM-specific risks for an app"],
    concepts: ["OWASP LLM Top 10", "attack surface", "trust boundaries"],
    commonMistakes: ["Treating LLM apps like ordinary CRUD apps"],
    masteryCriteria: "You can threat-model one of your own apps.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "core",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-api-first-call"],
    skillIds: ["skill-ai-security"],
    unitIds: ["unit-sec-threat-model-01", "unit-sec-threat-model-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-sec-prompt-injection",
    categoryId: "category-ai-security",
    order: 2,
    title: "Prompt Injection & Defenses",
    slug: "prompt-injection-defenses",
    shortDescription: "Direct/indirect injection, jailbreaks and layered mitigations.",
    whyItMatters: "Injection via retrieved/user content is the top LLM risk.",
    learningObjectives: ["Demonstrate injection", "Defend against it (esp. via RAG content)"],
    concepts: ["direct/indirect injection", "content isolation", "allow-lists", "output filtering"],
    commonMistakes: ["Trusting retrieved/user content as instructions"],
    masteryCriteria: "You harden a RAG app so untrusted docs can't hijack it.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-sec-threat-model", "topic-rag-basic-pipeline"],
    skillIds: ["skill-prompt-injection", "skill-ai-security"],
    unitIds: ["unit-sec-prompt-injection-01", "unit-sec-prompt-injection-02", "unit-sec-prompt-injection-03", "unit-sec-prompt-injection-04"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-sec-guardrails",
    categoryId: "category-ai-security",
    order: 3,
    title: "Guardrails, Moderation & Safe Output Handling",
    slug: "guardrails-moderation",
    shortDescription: "Input/output validation, content moderation, PII handling, safe tool execution and least privilege.",
    whyItMatters: "Guardrails prevent unsafe actions and outputs in production.",
    learningObjectives: ["Add guardrails and safe execution around LLM output/tools"],
    concepts: ["moderation APIs", "schema/output validation", "PII redaction", "sandboxing", "least privilege"],
    commonMistakes: ["Executing model output directly", "Over-privileged tools"],
    masteryCriteria: "You build an agent that can't be coerced into unsafe actions.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-sec-prompt-injection", "topic-agent-tool-calling"],
    skillIds: ["skill-guardrails", "skill-ai-security"],
    unitIds: ["unit-sec-guardrails-01", "unit-sec-guardrails-02", "unit-sec-guardrails-03", "unit-sec-guardrails-04"],
    relatedProjectIds: ["project-p4-agent"],
  },
  {
    id: "topic-sec-data-privacy",
    categoryId: "category-ai-security",
    order: 4,
    title: "Data Privacy, Secrets & Compliance Basics",
    slug: "data-privacy-compliance",
    shortDescription: "Key management, data residency, logging PII safely and enterprise/Azure considerations.",
    whyItMatters: "Responsible data handling is mandatory for enterprise AI.",
    learningObjectives: ["Handle secrets/PII and data residency responsibly"],
    concepts: ["secret management", "data residency", "private endpoints", "retention", "compliance basics"],
    commonMistakes: ["Logging prompts with PII", "Keys in code"],
    masteryCriteria: "You can write a data-handling policy for an AI app.",
    difficulty: "intermediate",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-sec-threat-model", "topic-py-env-tooling"],
    skillIds: ["skill-ai-security", "skill-env-tooling"],
    unitIds: ["unit-sec-data-privacy-01", "unit-sec-data-privacy-02"],
    relatedProjectIds: [],
  },

  // ── Category 14 · Deployment & Production AI Engineering ────────────────────
  {
    id: "topic-prod-api",
    categoryId: "category-production",
    order: 1,
    title: "Serving AI as an API (FastAPI)",
    slug: "serving-ai-api",
    shortDescription: "Build a production API around your AI app: endpoints, streaming, async and validation.",
    whyItMatters: "An app becomes a product when it's a robust, documented service.",
    learningObjectives: ["Wrap an AI app in a robust FastAPI service"],
    concepts: ["FastAPI", "pydantic", "async endpoints", "streaming (SSE)", "error handling"],
    commonMistakes: ["Blocking endpoints", "No validation", "Leaking internal errors"],
    masteryCriteria: "You build a documented, streaming AI API with proper error handling.",
    difficulty: "intermediate",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-py-async-http", "topic-rag-basic-pipeline"],
    skillIds: ["skill-fastapi", "skill-resilience"],
    unitIds: ["unit-prod-api-01", "unit-prod-api-02", "unit-prod-api-03", "unit-prod-api-04"],
    relatedProjectIds: ["project-p6-production-service"],
  },
  {
    id: "topic-prod-docker",
    categoryId: "category-production",
    order: 2,
    title: "Containerization with Docker",
    slug: "containerization-docker",
    shortDescription: "Dockerfiles, images, compose, env/secrets and slim images for AI apps.",
    whyItMatters: "Containers make deployments reproducible and portable.",
    learningObjectives: ["Containerize an AI service reproducibly"],
    concepts: ["Dockerfile", "images/layers", "compose", "env vars/secrets", "image size"],
    commonMistakes: ["Giant images", "Baking secrets into images"],
    masteryCriteria: "You produce a lean, reproducible container for your API.",
    difficulty: "intermediate",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-api", "topic-py-env-tooling"],
    skillIds: ["skill-docker"],
    unitIds: ["unit-prod-docker-01", "unit-prod-docker-02", "unit-prod-docker-03", "unit-prod-docker-04"],
    relatedProjectIds: ["project-p6-production-service"],
  },
  {
    id: "topic-prod-cloud-deploy",
    categoryId: "category-production",
    order: 3,
    title: "Deploying to the Cloud",
    slug: "cloud-deployment",
    shortDescription: "Deploy a container to a cloud service with config, scaling, env and logs.",
    whyItMatters: "A reachable, monitored deployment is the point of the work.",
    learningObjectives: ["Deploy your containerized API publicly with config & logging"],
    concepts: ["container hosting", "env/config", "scaling", "health checks", "logs"],
    commonMistakes: ["Manual snowflake deploys", "No health checks/logging"],
    masteryCriteria: "You have a reachable, monitored deployment of your AI API.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "core",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-docker"],
    skillIds: ["skill-cloud-deployment"],
    unitIds: ["unit-prod-cloud-deploy-01", "unit-prod-cloud-deploy-02", "unit-prod-cloud-deploy-03"],
    relatedProjectIds: ["project-p6-production-service"],
  },
  {
    id: "topic-prod-azure-ai",
    categoryId: "category-production",
    order: 4,
    title: "Azure AI Platform in Depth",
    slug: "azure-ai-platform",
    shortDescription: "Azure OpenAI, AI Search, AI Foundry, Container Apps and Key Vault — an enterprise reference stack.",
    whyItMatters: "Enterprise AI often runs on Azure; concepts stay transferable.",
    learningObjectives: ["Assemble an enterprise-grade AI app on Azure with secure config"],
    concepts: ["Azure OpenAI deployments", "AI Search", "Foundry", "Container Apps", "Key Vault", "managed identity"],
    commonMistakes: ["Portal-only clicks with no reproducibility", "Keys over managed identity"],
    masteryCriteria: "You build a secured Azure-hosted RAG app using managed identity + Key Vault.",
    difficulty: "advanced",
    estimatedHours: 9,
    track: "core",
    applicableStages: ["not-started", "learning", "practicing", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-cloud-deploy", "topic-vdb-azure-search"],
    skillIds: ["skill-azure-ai", "skill-cloud-deployment"],
    unitIds: ["unit-prod-azure-ai-01", "unit-prod-azure-ai-02", "unit-prod-azure-ai-03", "unit-prod-azure-ai-04"],
    relatedProjectIds: ["project-p6-production-service"],
  },
  {
    id: "topic-prod-cicd-ops",
    categoryId: "category-production",
    order: 5,
    title: "CI/CD, Monitoring & LLMOps",
    slug: "cicd-monitoring-llmops",
    shortDescription: "Pipelines, automated deploy, monitoring/alerting, cost dashboards, rollback and prompt/version management.",
    whyItMatters: "Operating AI reliably requires automation and monitoring.",
    learningObjectives: ["Automate deploy", "Operate the app with monitoring + eval gates", "Deliver Project P6"],
    concepts: ["CI/CD", "monitoring/alerting", "cost tracking", "rollback", "LLMOps lifecycle"],
    commonMistakes: ["Deploy-and-forget", "No rollback", "No cost alerts"],
    masteryCriteria: "You have a pipeline that tests, evals, deploys and monitors automatically.",
    difficulty: "advanced",
    estimatedHours: 8,
    track: "core",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-cloud-deploy", "topic-eval-ci", "topic-eval-observability"],
    skillIds: ["skill-llmops", "skill-observability", "skill-git-cicd"],
    unitIds: ["unit-prod-cicd-ops-01", "unit-prod-cicd-ops-02", "unit-prod-cicd-ops-03", "unit-prod-cicd-ops-04"],
    relatedProjectIds: ["project-p6-production-service"],
  },
  {
    id: "topic-prod-scaling-cost",
    categoryId: "category-production",
    order: 6,
    title: "Scaling, Caching & Cost Optimization",
    slug: "scaling-caching-cost",
    shortDescription: "Semantic/response caching, batching, model routing/fallback and latency & cost tuning.",
    whyItMatters: "Cost and latency decide whether an AI product is viable.",
    learningObjectives: ["Cut cost/latency without hurting quality"],
    concepts: ["caching", "batching", "model routing", "fallbacks", "autoscaling"],
    commonMistakes: ["Premature optimization", "Caching the wrong things"],
    masteryCriteria: "You achieve measurable cost/latency reduction with intact quality.",
    difficulty: "advanced",
    estimatedHours: 5,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-api", "topic-api-streaming-robustness"],
    skillIds: ["skill-cost-optimization", "skill-resilience"],
    unitIds: ["unit-prod-scaling-cost-01", "unit-prod-scaling-cost-02", "unit-prod-scaling-cost-03"],
    relatedProjectIds: ["project-p6-production-service"],
  },

  // ── Category 15 · Advanced Topics (optional-depth category) ─────────────────
  {
    id: "topic-adv-context-engineering",
    categoryId: "category-advanced",
    order: 1,
    title: "Context Engineering & Long-Context Systems",
    slug: "context-engineering",
    shortDescription: "Context assembly, long-context vs RAG tradeoffs, prompt/context caching and memory architectures.",
    whyItMatters: "Deliberate context design often beats naive RAG.",
    learningObjectives: ["Build a context-optimized pipeline", "Compare vs naive RAG"],
    concepts: ["context assembly", "long-context vs RAG", "prompt/context caching", "memory architectures"],
    commonMistakes: ["Stuffing context without a strategy"],
    masteryCriteria: "You build a context-optimized pipeline that outperforms naive RAG.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "useful",
    applicableStages: ["not-started", "learning", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-rag-quality", "topic-agent-memory-planning"],
    skillIds: ["skill-context-engineering", "skill-rag"],
    unitIds: ["unit-adv-context-engineering-01", "unit-adv-context-engineering-02", "unit-adv-context-engineering-03"],
    relatedProjectIds: ["project-p7-specialization"],
  },
  {
    id: "topic-adv-reasoning-models",
    categoryId: "category-advanced",
    order: 2,
    title: "Reasoning Models & Test-Time Compute",
    slug: "reasoning-models",
    shortDescription: "Reasoning-optimized models, when they're worth the cost and prompting differences.",
    whyItMatters: "Reasoning models change cost/quality tradeoffs for hard tasks.",
    learningObjectives: ["Compare reasoning models on hard tasks", "Analyze cost/quality"],
    concepts: ["reasoning models", "test-time compute", "prompting differences"],
    commonMistakes: ["Using reasoning models for trivial tasks"],
    masteryCriteria: "You can decide when a reasoning model is worth the extra cost.",
    difficulty: "advanced",
    estimatedHours: 6,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "practicing", "reviewing", "completed"],
    recommendedAfter: ["topic-api-reasoning-patterns"],
    skillIds: ["skill-ml-literacy", "skill-prompt-engineering"],
    unitIds: ["unit-adv-reasoning-models-01", "unit-adv-reasoning-models-02", "unit-adv-reasoning-models-03"],
    relatedProjectIds: [],
  },
  {
    id: "topic-adv-ml-literacy",
    categoryId: "category-advanced",
    order: 3,
    title: "Just-Enough ML Literacy",
    slug: "ml-literacy",
    shortDescription: "Conceptual training/gradients/overfitting/embeddings-origins — literacy only, no derivations.",
    whyItMatters: "A little ML literacy sharpens intuition without the researcher path.",
    learningObjectives: ["Explain key ML concepts at a literacy level"],
    concepts: ["training (conceptual)", "gradients (conceptual)", "overfitting", "embeddings origins"],
    commonMistakes: ["Diving into heavy math not needed for the role"],
    masteryCriteria: "You can explain-back the key ideas without derivations.",
    difficulty: "intermediate",
    estimatedHours: 6,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-llm-what-are"],
    skillIds: ["skill-ml-literacy"],
    unitIds: ["unit-adv-ml-literacy-01", "unit-adv-ml-literacy-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-adv-emerging",
    categoryId: "category-advanced",
    order: 4,
    title: "Emerging Patterns & Continuous Learning",
    slug: "emerging-patterns",
    shortDescription: "Tracking the field responsibly — papers-with-skepticism, changelogs, protocols and new modalities.",
    whyItMatters: "AI moves fast; a sustainable learning practice keeps you current.",
    learningObjectives: ["Maintain a personal 'what changed' learning practice"],
    concepts: ["reading with skepticism", "changelogs", "protocols (MCP/A2A)", "new modalities"],
    commonMistakes: ["Chasing every hype cycle"],
    masteryCriteria: "You maintain a durable habit for staying current.",
    difficulty: "advanced",
    estimatedHours: 4,
    track: "optional-depth",
    applicableStages: ["not-started", "learning", "reviewing", "completed"],
    recommendedAfter: ["topic-prod-cicd-ops"],
    skillIds: ["skill-continuous-learning"],
    unitIds: ["unit-adv-emerging-01", "unit-adv-emerging-02"],
    relatedProjectIds: [],
  },
  {
    id: "topic-adv-specialization-capstone",
    categoryId: "category-advanced",
    order: 5,
    title: "Specialization Capstone",
    slug: "specialization-capstone",
    shortDescription: "A self-directed advanced project in a chosen niche (agents, multimodal, RAG-at-scale, etc.).",
    whyItMatters: "Depth in a niche differentiates you and polishes your portfolio.",
    learningObjectives: ["Build a niche advanced system", "Deliver Project P7"],
    concepts: ["self-directed specialization", "portfolio polish", "write-up"],
    commonMistakes: ["Choosing a niche with no real deliverable"],
    masteryCriteria: "You ship a niche advanced system with a strong write-up.",
    difficulty: "advanced",
    estimatedHours: 7,
    track: "optional-depth",
    applicableStages: ["not-started", "building", "reviewing", "completed"],
    recommendedAfter: ["topic-adv-context-engineering"],
    skillIds: ["skill-continuous-learning"],
    unitIds: ["unit-adv-specialization-capstone-01", "unit-adv-specialization-capstone-02", "unit-adv-specialization-capstone-03"],
    relatedProjectIds: ["project-p7-specialization"],
  },
];
