import type { LearningUnit } from "./types";

// Learning units for categories 5–9.
export const unitsPartB: LearningUnit[] = [
  // 5.1 Why Vector Databases
  { id: "unit-vdb-concepts-01", topicId: "topic-vdb-concepts", order: 1, title: "ANN & indexes conceptually", description: "ANN vs brute force, HNSW/IVF.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn ANN tradeoffs at a conceptual level.", completionCriteria: "You can explain recall vs latency.", skillIds: ["skill-vector-databases"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-vdb-concepts-02", topicId: "topic-vdb-concepts", order: 2, title: "DB-vs-memory decision", description: "Decide for several scenarios.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Decide vector-DB vs in-memory for scenarios.", completionCriteria: "Each decision is justified on scale/latency.", skillIds: ["skill-vector-databases"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-concepts-01"] },

  // 5.2 Using a Vector Database
  { id: "unit-vdb-hands-on-01", topicId: "topic-vdb-hands-on", order: 1, title: "Vector DB basics", description: "Collections, upserts, queries.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn vector DB CRUD operations.", completionCriteria: "You can describe upsert and query flow.", skillIds: ["skill-vector-databases"], resourceIds: ["resource-vector-db-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-vdb-hands-on-02", topicId: "topic-vdb-hands-on", order: 2, title: "Upsert/query sample vectors", description: "Practice CRUD operations.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Upsert and query sample vectors with metadata.", completionCriteria: "Top-k queries return expected items.", skillIds: ["skill-vector-databases"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-hands-on-01"] },
  { id: "unit-vdb-hands-on-03", topicId: "topic-vdb-hands-on", order: 3, title: "Port P2 to a vector DB", description: "Migrate in-memory search.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Port the semantic-search core onto a real vector DB.", completionCriteria: "Search runs on a persistent vector DB.", skillIds: ["skill-vector-databases"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-hands-on-02"] },
  { id: "unit-vdb-hands-on-04", topicId: "topic-vdb-hands-on", order: 4, title: "Benchmark vs in-memory", description: "Compare latency.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Benchmark vector-DB latency vs in-memory.", completionCriteria: "You quantify the latency difference.", skillIds: ["skill-vector-databases"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-hands-on-03"] },

  // 5.3 Metadata Filtering & Hybrid Search
  { id: "unit-vdb-metadata-hybrid-01", topicId: "topic-vdb-metadata-hybrid", order: 1, title: "Hybrid & filtering", description: "Metadata filters, hybrid, rerankers.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "advanced", instructions: "Learn metadata filtering, hybrid search and reranking.", completionCriteria: "You can describe keyword+vector fusion.", skillIds: ["skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-vdb-metadata-hybrid-02", topicId: "topic-vdb-metadata-hybrid", order: 2, title: "Add metadata filters", description: "Filter results by metadata.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Add metadata filtering to queries.", completionCriteria: "Filters correctly scope results.", skillIds: ["skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-metadata-hybrid-01"] },
  { id: "unit-vdb-metadata-hybrid-03", topicId: "topic-vdb-metadata-hybrid", order: 3, title: "Hybrid search + reranker", description: "Fuse keyword + vector and rerank.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build hybrid search with a reranker.", completionCriteria: "Hybrid search returns improved results.", skillIds: ["skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-metadata-hybrid-02"] },
  { id: "unit-vdb-metadata-hybrid-04", topicId: "topic-vdb-metadata-hybrid", order: 4, title: "Vector vs hybrid quality", description: "Compare quality.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare vector-only vs hybrid retrieval quality.", completionCriteria: "You demonstrate hybrid's advantage on your data.", skillIds: ["skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-metadata-hybrid-03"] },

  // 5.4 Azure AI Search
  { id: "unit-vdb-azure-search-01", topicId: "topic-vdb-azure-search", order: 1, title: "Azure AI Search", description: "Indexes, indexers, vectorization.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn Azure AI Search index design.", completionCriteria: "You can describe integrated vectorization.", skillIds: ["skill-azure-ai"], resourceIds: ["resource-azure-ai-search-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-vdb-azure-search-02", topicId: "topic-vdb-azure-search", order: 2, title: "Create/query an index", description: "Build and query an index.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Create an Azure AI Search index and query it.", completionCriteria: "Vector + filter queries return results.", skillIds: ["skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-azure-search-01"] },
  { id: "unit-vdb-azure-search-03", topicId: "topic-vdb-azure-search", order: 3, title: "Back P2/P3 with Azure AI Search", description: "Use it as the retrieval store.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Back a retrieval app with Azure AI Search.", completionCriteria: "App retrieves from Azure AI Search.", skillIds: ["skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-vdb-azure-search-02"] },

  // 6.1 RAG Fundamentals
  { id: "unit-rag-concepts-01", topicId: "topic-rag-concepts", order: 1, title: "RAG loop & tradeoffs", description: "Retrieve→augment→generate.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn the RAG loop and when to use it.", completionCriteria: "You can sketch a RAG pipeline.", skillIds: ["skill-rag"], resourceIds: ["resource-rag-overview"], recommendedAfterUnitIds: [] },
  { id: "unit-rag-concepts-02", topicId: "topic-rag-concepts", order: 2, title: "Choose the right approach", description: "RAG vs fine-tune vs long-context.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Choose RAG or an alternative for scenarios.", completionCriteria: "Each choice is justified.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-concepts-01"] },

  // 6.2 Building a Basic RAG Pipeline
  { id: "unit-rag-basic-pipeline-01", topicId: "topic-rag-basic-pipeline", order: 1, title: "Pipeline anatomy", description: "Ingest→retrieve→prompt→answer.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn the anatomy of a RAG pipeline.", completionCriteria: "You can list each pipeline stage.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-rag-basic-pipeline-02", topicId: "topic-rag-basic-pipeline", order: 2, title: "Assemble grounded prompts", description: "Inject retrieved context.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Assemble grounded prompts from retrieved chunks.", completionCriteria: "Prompts include cited context.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-basic-pipeline-01"] },
  { id: "unit-rag-basic-pipeline-03", topicId: "topic-rag-basic-pipeline", order: 3, title: "Full RAG with citations", description: "End-to-end RAG over docs.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Build full RAG over a document set with citations.", completionCriteria: "App answers from docs and cites sources.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-basic-pipeline-02"] },
  { id: "unit-rag-basic-pipeline-04", topicId: "topic-rag-basic-pipeline", order: 4, title: "Inspect failure cases", description: "Find where RAG fails.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Inspect RAG failure cases.", completionCriteria: "You classify failures as retrieval or generation.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-basic-pipeline-03"] },

  // 6.3 Improving Retrieval Quality
  { id: "unit-rag-quality-01", topicId: "topic-rag-quality", order: 1, title: "Retrieval improvements", description: "Reranking, rewriting, HyDE, hybrid.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn retrieval-quality techniques.", completionCriteria: "You can name techniques and when to use them.", skillIds: ["skill-retrieval-quality"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-rag-quality-02", topicId: "topic-rag-quality", order: 2, title: "Add query rewriting", description: "Rewrite/expand queries.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Add query rewriting to your RAG app.", completionCriteria: "Rewriting improves recall.", skillIds: ["skill-retrieval-quality"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-quality-01"] },
  { id: "unit-rag-quality-03", topicId: "topic-rag-quality", order: 3, title: "Reranked hybrid RAG", description: "Combine hybrid + reranking.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build reranked hybrid RAG.", completionCriteria: "Retrieval relevance measurably improves.", skillIds: ["skill-retrieval-quality", "skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-quality-02"] },
  { id: "unit-rag-quality-04", topicId: "topic-rag-quality", order: 4, title: "Before/after relevance", description: "Compare improvements.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare relevance before and after changes.", completionCriteria: "You quantify the improvement.", skillIds: ["skill-retrieval-quality"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-quality-03"] },

  // 6.4 Evaluating RAG
  { id: "unit-rag-evaluation-01", topicId: "topic-rag-evaluation", order: 1, title: "RAG metrics", description: "Faithfulness, relevance, groundedness.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn RAG evaluation metrics.", completionCriteria: "You can define faithfulness and relevance.", skillIds: ["skill-evaluation"], resourceIds: ["resource-rag-eval-framework"], recommendedAfterUnitIds: [] },
  { id: "unit-rag-evaluation-02", topicId: "topic-rag-evaluation", order: 2, title: "Label a small eval set", description: "Create labeled examples.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Label a small RAG evaluation set.", completionCriteria: "You have a usable labeled eval set.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-evaluation-01"] },
  { id: "unit-rag-evaluation-03", topicId: "topic-rag-evaluation", order: 3, title: "Build an eval harness", description: "Ragas-style automated eval.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build a RAG eval harness.", completionCriteria: "Harness produces faithfulness/relevance scores.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-evaluation-02"] },
  { id: "unit-rag-evaluation-04", topicId: "topic-rag-evaluation", order: 4, title: "Interpret scores & act", description: "Turn scores into fixes.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Interpret eval scores and decide actions.", completionCriteria: "You act on the eval findings.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-evaluation-03"] },

  // 6.5 Advanced RAG Patterns (P3 anchor)
  { id: "unit-rag-advanced-patterns-01", topicId: "topic-rag-advanced-patterns", order: 1, title: "Advanced patterns", description: "Multi-hop, hierarchical, contextual, graph.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn advanced RAG patterns.", completionCriteria: "You can match a pattern to a gap.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-rag-advanced-patterns-02", topicId: "topic-rag-advanced-patterns", order: 2, title: "Implement one pattern", description: "Apply a pattern on the P3 app.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Implement one advanced pattern on Project P3.", completionCriteria: "The pattern addresses a real gap.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-advanced-patterns-01"] },
  { id: "unit-rag-advanced-patterns-03", topicId: "topic-rag-advanced-patterns", order: 3, title: "Improvement vs added cost", description: "Was it worth it?", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Measure improvement vs added complexity/cost.", completionCriteria: "You justify keeping or dropping the pattern.", skillIds: ["skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-advanced-patterns-02"] },
  { id: "unit-rag-advanced-patterns-04", topicId: "topic-rag-advanced-patterns", order: 4, title: "Deliver Project P3", description: "Finalize the RAG application.", mode: "project", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Combine the category into the P3 RAG application.", completionCriteria: "P3 is grounded, evaluated and served.", skillIds: ["skill-rag", "skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-rag-advanced-patterns-03"] },

  // 7.1 Why Frameworks
  { id: "unit-orch-why-01", topicId: "topic-orch-why", order: 1, title: "Framework value & cost", description: "Abstractions and lock-in.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn what frameworks provide and their costs.", completionCriteria: "You can weigh framework tradeoffs.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-orch-why-02", topicId: "topic-orch-why", order: 2, title: "Decide for scenarios", description: "Framework vs framework-free.", mode: "review", stage: "reviewing", estimatedMinutes: 45, difficulty: "intermediate", instructions: "Decide framework use for several scenarios.", completionCriteria: "Each decision is justified.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-why-01"] },

  // 7.2 LangChain Essentials
  { id: "unit-orch-langchain-01", topicId: "topic-orch-langchain", order: 1, title: "LangChain core", description: "Chains/LCEL, retrievers, memory, tools.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Learn LangChain core abstractions.", completionCriteria: "You can explain LCEL composition.", skillIds: ["skill-orchestration"], resourceIds: ["resource-langchain-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-orch-langchain-02", topicId: "topic-orch-langchain", order: 2, title: "Compose simple chains", description: "Build small chains.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Compose simple chains with LCEL.", completionCriteria: "Chains run and are inspectable.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-langchain-01"] },
  { id: "unit-orch-langchain-03", topicId: "topic-orch-langchain", order: 3, title: "Reimplement P3 in LangChain", description: "Rebuild RAG with LangChain.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Reimplement the RAG app using LangChain.", completionCriteria: "LangChain RAG matches prior behavior.", skillIds: ["skill-orchestration", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-langchain-02"] },
  { id: "unit-orch-langchain-04", topicId: "topic-orch-langchain", order: 4, title: "Compare to framework-free", description: "Framework vs hand-rolled.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Compare the LangChain version to your framework-free one.", completionCriteria: "You articulate concrete tradeoffs.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-langchain-03"] },

  // 7.3 LlamaIndex
  { id: "unit-orch-llamaindex-01", topicId: "topic-orch-llamaindex", order: 1, title: "LlamaIndex model", description: "Documents/nodes, indices, query engines.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn the LlamaIndex data model.", completionCriteria: "You can describe indices and query engines.", skillIds: ["skill-orchestration"], resourceIds: ["resource-llamaindex-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-orch-llamaindex-02", topicId: "topic-orch-llamaindex", order: 2, title: "Ingest & query a dataset", description: "Build ingestion + query.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Ingest and query a dataset with LlamaIndex.", completionCriteria: "Queries return grounded answers.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-llamaindex-01"] },
  { id: "unit-orch-llamaindex-03", topicId: "topic-orch-llamaindex", order: 3, title: "Document Q&A with LlamaIndex", description: "Build a Q&A app.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build a document Q&A using LlamaIndex.", completionCriteria: "Q&A app answers from your documents.", skillIds: ["skill-orchestration", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-llamaindex-02"] },

  // 7.4 LangGraph
  { id: "unit-orch-langgraph-01", topicId: "topic-orch-langgraph", order: 1, title: "Graph orchestration", description: "Nodes/edges, state, branching.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn stateful graph orchestration.", completionCriteria: "You can model a flow as a graph.", skillIds: ["skill-orchestration"], resourceIds: ["resource-langgraph-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-orch-langgraph-02", topicId: "topic-orch-langgraph", order: 2, title: "Stateful multi-step workflow", description: "Build a controllable flow.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build a stateful multi-step workflow.", completionCriteria: "Flow has explicit state and branching.", skillIds: ["skill-orchestration", "skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-langgraph-01"] },
  { id: "unit-orch-langgraph-03", topicId: "topic-orch-langgraph", order: 3, title: "Control vs plain chain", description: "Compare control.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare graph control to a plain chain.", completionCriteria: "You explain when a graph is warranted.", skillIds: ["skill-orchestration"], resourceIds: [], recommendedAfterUnitIds: ["unit-orch-langgraph-02"] },

  // 8.1 What Agents Are
  { id: "unit-agent-concepts-01", topicId: "topic-agent-concepts", order: 1, title: "Agent architectures", description: "ReAct loop, autonomy, termination.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn the agent loop and autonomy spectrum.", completionCriteria: "You can explain reason→act→observe.", skillIds: ["skill-agents"], resourceIds: ["resource-agent-patterns"], recommendedAfterUnitIds: [] },
  { id: "unit-agent-concepts-02", topicId: "topic-agent-concepts", order: 2, title: "Agent vs pipeline", description: "Classify tasks.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Classify tasks as agent or pipeline.", completionCriteria: "Each classification is justified.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-concepts-01"] },

  // 8.2 Tool / Function Calling in Depth
  { id: "unit-agent-tool-calling-01", topicId: "topic-agent-tool-calling", order: 1, title: "Tool calling mechanics", description: "Schemas, validation, execution.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn robust tool-calling mechanics.", completionCriteria: "You can define a validated tool schema.", skillIds: ["skill-tool-calling"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-agent-tool-calling-02", topicId: "topic-agent-tool-calling", order: 2, title: "Define & validate tool schemas", description: "Practice tool definitions.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Define and validate several tool schemas.", completionCriteria: "Arguments validate before execution.", skillIds: ["skill-tool-calling"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-tool-calling-01"] },
  { id: "unit-agent-tool-calling-03", topicId: "topic-agent-tool-calling", order: 3, title: "Agent with 2–3 real tools", description: "Search, calculator, API.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build an agent that calls 2–3 real tools.", completionCriteria: "Agent uses tools to complete tasks.", skillIds: ["skill-tool-calling", "skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-tool-calling-02"] },
  { id: "unit-agent-tool-calling-04", topicId: "topic-agent-tool-calling", order: 4, title: "Adversarial tool inputs", description: "Test bad args and failures.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Test the agent with adversarial tool inputs.", completionCriteria: "Agent handles bad args gracefully.", skillIds: ["skill-tool-calling"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-tool-calling-03"] },

  // 8.3 Agent Memory, Planning & Multi-step
  { id: "unit-agent-memory-planning-01", topicId: "topic-agent-memory-planning", order: 1, title: "Memory & planning", description: "Working/long-term memory, step limits.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn agent memory and bounded planning.", completionCriteria: "You can describe termination criteria.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-agent-memory-planning-02", topicId: "topic-agent-memory-planning", order: 2, title: "Add memory to your agent", description: "Give the agent memory.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Add working memory to your agent.", completionCriteria: "Agent recalls prior steps.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-memory-planning-01"] },
  { id: "unit-agent-memory-planning-03", topicId: "topic-agent-memory-planning", order: 3, title: "Multi-step agent w/ limits", description: "Step/cost bounds.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build a multi-step agent with step/cost limits.", completionCriteria: "Agent terminates within budget.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-memory-planning-02"] },
  { id: "unit-agent-memory-planning-04", topicId: "topic-agent-memory-planning", order: 4, title: "Stress-test for loops", description: "Verify termination.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Stress-test the agent for infinite loops.", completionCriteria: "Agent never loops unbounded.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-memory-planning-03"] },

  // 8.4 Agent Frameworks & Standards (MCP)
  { id: "unit-agent-frameworks-protocols-01", topicId: "topic-agent-frameworks-protocols", order: 1, title: "Frameworks & MCP", description: "Agent frameworks and MCP.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn agent frameworks and the Model Context Protocol.", completionCriteria: "You can describe MCP tool servers.", skillIds: ["skill-mcp"], resourceIds: ["resource-mcp-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-agent-frameworks-protocols-02", topicId: "topic-agent-frameworks-protocols", order: 2, title: "MCP-connected tool + agent", description: "Wire an agent to MCP tools.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build an MCP-connected tool and agent.", completionCriteria: "Agent uses tools via a standard protocol.", skillIds: ["skill-mcp", "skill-tool-calling"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-frameworks-protocols-01"] },
  { id: "unit-agent-frameworks-protocols-03", topicId: "topic-agent-frameworks-protocols", order: 3, title: "Framework vs hand-rolled", description: "Compare approaches.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare framework agents to hand-rolled ones.", completionCriteria: "You articulate the tradeoffs.", skillIds: ["skill-mcp"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-frameworks-protocols-02"] },

  // 8.5 Multi-Agent (P4 anchor, optional-depth)
  { id: "unit-agent-multiagent-01", topicId: "topic-agent-multiagent", order: 1, title: "Multi-agent patterns", description: "Roles, orchestrator/worker, handoffs.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "advanced", instructions: "Learn multi-agent patterns and their costs.", completionCriteria: "You can describe orchestrator/worker.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-agent-multiagent-02", topicId: "topic-agent-multiagent", order: 2, title: "2-agent collaboration", description: "Build a minimal example.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build a two-agent collaboration.", completionCriteria: "Two agents cooperate on a task.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-multiagent-01"] },
  { id: "unit-agent-multiagent-03", topicId: "topic-agent-multiagent", order: 3, title: "Compare to single-agent", description: "Judge the ROI.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare multi-agent to a single-agent baseline.", completionCriteria: "You judge multi-agent ROI critically.", skillIds: ["skill-agents"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-multiagent-02"] },
  { id: "unit-agent-multiagent-04", topicId: "topic-agent-multiagent", order: 4, title: "Deliver Project P4", description: "Finalize the tool-using agent.", mode: "project", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Combine agent skills into Project P4 with guardrails.", completionCriteria: "P4 is a bounded, safe tool-using agent.", skillIds: ["skill-agents", "skill-tool-calling"], resourceIds: [], recommendedAfterUnitIds: ["unit-agent-multiagent-03"] },

  // 9.1 Vision & Image Understanding
  { id: "unit-mm-vision-01", topicId: "topic-mm-vision", order: 1, title: "Vision models", description: "Image inputs, OCR, doc understanding.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn vision-capable models and document understanding.", completionCriteria: "You can send an image and read the result.", skillIds: ["skill-multimodal"], resourceIds: ["resource-vision-api-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-mm-vision-02", topicId: "topic-mm-vision", order: 2, title: "Describe/analyze images", description: "Practice vision prompts.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Analyze several images with a vision model.", completionCriteria: "You extract useful info from images.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-vision-01"] },
  { id: "unit-mm-vision-03", topicId: "topic-mm-vision", order: 3, title: "Document-data extractor", description: "Image → structured JSON.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build an image-to-JSON document extractor.", completionCriteria: "Extractor returns validated structured data.", skillIds: ["skill-multimodal", "skill-structured-outputs"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-vision-02"] },
  { id: "unit-mm-vision-04", topicId: "topic-mm-vision", order: 4, title: "Test edge-case images", description: "Try hard inputs.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Test the extractor on edge-case images.", completionCriteria: "Extractor degrades gracefully.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-vision-03"] },

  // 9.2 Speech & Audio
  { id: "unit-mm-speech-audio-01", topicId: "topic-mm-speech-audio", order: 1, title: "STT/TTS", description: "Speech-to-text and text-to-speech.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn STT and TTS pipelines.", completionCriteria: "You can describe a voice pipeline.", skillIds: ["skill-multimodal"], resourceIds: ["resource-speech-api-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-mm-speech-audio-02", topicId: "topic-mm-speech-audio", order: 2, title: "Transcribe a clip", description: "Practice transcription.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Transcribe an audio clip.", completionCriteria: "Transcript is accurate.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-speech-audio-01"] },
  { id: "unit-mm-speech-audio-03", topicId: "topic-mm-speech-audio", order: 3, title: "Voice Q&A pipeline", description: "Audio → text → LLM → speech.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build a voice Q&A pipeline.", completionCriteria: "Pipeline answers spoken questions aloud.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-speech-audio-02"] },

  // 9.3 Image Generation
  { id: "unit-mm-image-gen-01", topicId: "topic-mm-image-gen", order: 1, title: "Image-gen APIs", description: "Text-to-image and editing.", mode: "learn", stage: "learning", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Learn image generation and safety.", completionCriteria: "You can generate an image via API.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-mm-image-gen-02", topicId: "topic-mm-image-gen", order: 2, title: "Generate/iterate images", description: "Prompt for images.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Generate and iterate on images.", completionCriteria: "You control image output via prompts.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-image-gen-01"] },
  { id: "unit-mm-image-gen-03", topicId: "topic-mm-image-gen", order: 3, title: "Image-gen feature + safety", description: "Add content safety.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build an image-gen feature with safety checks.", completionCriteria: "Feature enforces content safety.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-image-gen-02"] },

  // 9.4 Multimodal RAG (P5 anchor)
  { id: "unit-mm-multimodal-rag-01", topicId: "topic-mm-multimodal-rag", order: 1, title: "Multimodal retrieval", description: "Image+text retrieval, tables/figures.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn multimodal retrieval.", completionCriteria: "You can describe handling of figures/tables.", skillIds: ["skill-multimodal", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-mm-multimodal-rag-02", topicId: "topic-mm-multimodal-rag", order: 2, title: "PDF-with-figures RAG", description: "Answer from figures/tables.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build RAG over PDFs containing figures/tables.", completionCriteria: "App answers grounded in figures/tables.", skillIds: ["skill-multimodal", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-multimodal-rag-01"] },
  { id: "unit-mm-multimodal-rag-03", topicId: "topic-mm-multimodal-rag", order: 3, title: "Compare vs text-only RAG", description: "Measure the gain.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Compare multimodal RAG to text-only.", completionCriteria: "You quantify the multimodal advantage.", skillIds: ["skill-multimodal"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-multimodal-rag-02"] },
  { id: "unit-mm-multimodal-rag-04", topicId: "topic-mm-multimodal-rag", order: 4, title: "Deliver Project P5", description: "Finalize the multimodal app.", mode: "project", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Combine multimodal skills into Project P5.", completionCriteria: "P5 is a non-chatbot multimodal application.", skillIds: ["skill-multimodal", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-mm-multimodal-rag-03"] },
];
