import type { LearningUnit } from "./types";

// Learning units for categories 10–15.
export const unitsPartC: LearningUnit[] = [
  // 10.1 Hugging Face Ecosystem
  { id: "unit-oss-huggingface-01", topicId: "topic-oss-huggingface", order: 1, title: "HF ecosystem", description: "Hub, transformers, pipelines, model cards.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Learn the Hugging Face ecosystem.", completionCriteria: "You can load a model and read its card.", skillIds: ["skill-open-models"], resourceIds: ["resource-huggingface-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-oss-huggingface-02", topicId: "topic-oss-huggingface", order: 2, title: "Run a text pipeline", description: "Inference via pipelines.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Run inference with a transformers pipeline.", completionCriteria: "Pipeline produces expected output.", skillIds: ["skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-huggingface-01"] },
  { id: "unit-oss-huggingface-03", topicId: "topic-oss-huggingface", order: 3, title: "Classifier/summarizer", description: "Build with an open model.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build a small classifier or summarizer.", completionCriteria: "App runs on an open model locally.", skillIds: ["skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-huggingface-02"] },

  // 10.2 Running Models Locally
  { id: "unit-oss-local-inference-01", topicId: "topic-oss-local-inference", order: 1, title: "Local runtimes & quantization", description: "Ollama/llama.cpp, GGUF, quant.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn local runtimes and quantization.", completionCriteria: "You can pick a quant for your hardware.", skillIds: ["skill-open-models"], resourceIds: ["resource-ollama-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-oss-local-inference-02", topicId: "topic-oss-local-inference", order: 2, title: "Run a model in Ollama", description: "Local inference hands-on.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Run a quantized model locally.", completionCriteria: "Model responds locally.", skillIds: ["skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-local-inference-01"] },
  { id: "unit-oss-local-inference-03", topicId: "topic-oss-local-inference", order: 3, title: "Swap backend to local", description: "Point your app at a local model.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Swap an app's backend to a local model.", completionCriteria: "App calls the local model from code.", skillIds: ["skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-local-inference-02"] },
  { id: "unit-oss-local-inference-04", topicId: "topic-oss-local-inference", order: 4, title: "Quality/latency/cost vs hosted", description: "Compare local vs hosted.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Compare local vs hosted on quality/latency/cost.", completionCriteria: "You make an evidence-based choice.", skillIds: ["skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-local-inference-03"] },

  // 10.3 Serving Open Models
  { id: "unit-oss-serving-01", topicId: "topic-oss-serving", order: 1, title: "Serving stacks", description: "vLLM/TGI, OpenAI-compatible.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn model-serving stacks.", completionCriteria: "You can describe an OpenAI-compatible endpoint.", skillIds: ["skill-model-serving"], resourceIds: ["resource-vllm-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-oss-serving-02", topicId: "topic-oss-serving", order: 2, title: "Serve behind OpenAI-compatible API", description: "Expose a model endpoint.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Serve an open model behind an OpenAI-compatible API.", completionCriteria: "Your app calls it like any provider.", skillIds: ["skill-model-serving"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-serving-01"] },
  { id: "unit-oss-serving-03", topicId: "topic-oss-serving", order: 3, title: "Load-test throughput", description: "Basic concurrency test.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Load-test basic throughput.", completionCriteria: "You measure requests/sec under load.", skillIds: ["skill-model-serving"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-serving-02"] },

  // 10.4 Local Embeddings & Rerankers
  { id: "unit-oss-embeddings-local-01", topicId: "topic-oss-embeddings-local", order: 1, title: "Open embeddings/rerankers", description: "SBERT/BGE, cross-encoders.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn open embedding models and rerankers.", completionCriteria: "You can pick an open embedding model.", skillIds: ["skill-open-models", "skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-oss-embeddings-local-02", topicId: "topic-oss-embeddings-local", order: 2, title: "Embed locally", description: "Generate embeddings offline.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Generate embeddings with a local model.", completionCriteria: "Local vectors match expected dimension.", skillIds: ["skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-embeddings-local-01"] },
  { id: "unit-oss-embeddings-local-03", topicId: "topic-oss-embeddings-local", order: 3, title: "Swap RAG to local", description: "Local embeddings + reranker.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Swap RAG to local embeddings and reranker.", completionCriteria: "RAG runs on a fully local retrieval stack.", skillIds: ["skill-embeddings", "skill-hybrid-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-oss-embeddings-local-02"] },

  // 11.1 When to Fine-Tune
  { id: "unit-ft-when-01", topicId: "topic-ft-when", order: 1, title: "Decision framework", description: "Prompt → RAG → fine-tune.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn when fine-tuning is warranted.", completionCriteria: "You can apply the decision framework.", skillIds: ["skill-fine-tuning"], resourceIds: ["resource-finetuning-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-ft-when-02", topicId: "topic-ft-when", order: 2, title: "Classify cases correctly", description: "Decide fine-tune vs not.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Classify cases as fine-tune or not.", completionCriteria: "Each classification is justified.", skillIds: ["skill-fine-tuning"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-when-01"] },

  // 11.2 Datasets for Fine-Tuning
  { id: "unit-ft-data-01", topicId: "topic-ft-data", order: 1, title: "Dataset design", description: "Instruction data, quality, splits.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn fine-tuning dataset design.", completionCriteria: "You can describe good dataset properties.", skillIds: ["skill-fine-tuning"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-ft-data-02", topicId: "topic-ft-data", order: 2, title: "Format samples", description: "Format instruction examples.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Format instruction-tuning samples.", completionCriteria: "Samples follow a consistent schema.", skillIds: ["skill-fine-tuning"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-data-01"] },
  { id: "unit-ft-data-03", topicId: "topic-ft-data", order: 3, title: "Assemble a small dataset", description: "Build a validated dataset.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Assemble a small instruction dataset with splits.", completionCriteria: "Dataset is clean and split for training.", skillIds: ["skill-fine-tuning", "skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-data-02"] },

  // 11.3 Hosted Fine-Tuning
  { id: "unit-ft-hosted-01", topicId: "topic-ft-hosted", order: 1, title: "Hosted fine-tuning", description: "Managed workflow and eval.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn hosted fine-tuning workflow.", completionCriteria: "You can outline the managed workflow.", skillIds: ["skill-fine-tuning", "skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-ft-hosted-02", topicId: "topic-ft-hosted", order: 2, title: "Fine-tune + deploy on Azure", description: "Run and deploy a fine-tune.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Run and deploy a hosted fine-tune on Azure OpenAI.", completionCriteria: "A fine-tuned model is deployed.", skillIds: ["skill-fine-tuning", "skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-hosted-01"] },
  { id: "unit-ft-hosted-03", topicId: "topic-ft-hosted", order: 3, title: "Eval vs base model", description: "Prove the improvement.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Evaluate the fine-tune against the base model.", completionCriteria: "Fine-tune beats base on your eval.", skillIds: ["skill-fine-tuning", "skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-hosted-02"] },

  // 11.4 PEFT / LoRA (optional-depth)
  { id: "unit-ft-lora-01", topicId: "topic-ft-lora", order: 1, title: "PEFT concepts", description: "LoRA/QLoRA, adapters.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn parameter-efficient fine-tuning.", completionCriteria: "You can explain adapters.", skillIds: ["skill-fine-tuning"], resourceIds: ["resource-peft-lora-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-ft-lora-02", topicId: "topic-ft-lora", order: 2, title: "QLoRA run on a small model", description: "Practical PEFT run.", mode: "build", stage: "building", estimatedMinutes: 240, difficulty: "advanced", instructions: "Run a QLoRA fine-tune on a small model.", completionCriteria: "You produce a LoRA adapter.", skillIds: ["skill-fine-tuning", "skill-open-models"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-lora-01"] },
  { id: "unit-ft-lora-03", topicId: "topic-ft-lora", order: 3, title: "Adapter vs base", description: "Compare results.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Compare the adapter to the base model.", completionCriteria: "You quantify the adapter's effect.", skillIds: ["skill-fine-tuning"], resourceIds: [], recommendedAfterUnitIds: ["unit-ft-lora-02"] },

  // 12.1 Why Evaluation Is Hard
  { id: "unit-eval-why-01", topicId: "topic-eval-why", order: 1, title: "Eval challenges", description: "Non-determinism, no ground truth.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn why generative eval is hard.", completionCriteria: "You can frame eval for a fuzzy task.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-eval-why-02", topicId: "topic-eval-why", order: 2, title: "Critique naive eval plans", description: "Spot flawed eval.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Critique several naive evaluation plans.", completionCriteria: "You identify each plan's flaw.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-why-01"] },

  // 12.2 Evaluation Methods & Metrics
  { id: "unit-eval-methods-01", topicId: "topic-eval-methods", order: 1, title: "Methods & metrics", description: "LLM-as-judge, rubrics, golden sets.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn evaluation methods and metrics.", completionCriteria: "You can pick a method for a task.", skillIds: ["skill-evaluation"], resourceIds: ["resource-eval-methods-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-eval-methods-02", topicId: "topic-eval-methods", order: 2, title: "Judge prompt + rubric", description: "Write an LLM judge.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Write a judge prompt and rubric.", completionCriteria: "Judge scores align with intent.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-methods-01"] },
  { id: "unit-eval-methods-03", topicId: "topic-eval-methods", order: 3, title: "Eval suite for an app", description: "Build an eval suite.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build an eval suite for one of your apps.", completionCriteria: "Suite produces trustworthy scores.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-methods-02"] },
  { id: "unit-eval-methods-04", topicId: "topic-eval-methods", order: 4, title: "Validate judge vs humans", description: "Check judge reliability.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Validate the LLM judge against human labels.", completionCriteria: "Judge agreement with humans is measured.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-methods-03"] },

  // 12.3 Tracing & Observability
  { id: "unit-eval-observability-01", topicId: "topic-eval-observability", order: 1, title: "Observability", description: "Tracing, spans, prompt versioning.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn LLM observability.", completionCriteria: "You can describe a trace/span.", skillIds: ["skill-observability"], resourceIds: ["resource-observability-tools"], recommendedAfterUnitIds: [] },
  { id: "unit-eval-observability-02", topicId: "topic-eval-observability", order: 2, title: "Add tracing to an app", description: "Instrument LLM calls.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Add tracing to an existing app.", completionCriteria: "Requests are traced end-to-end.", skillIds: ["skill-observability"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-observability-01"] },
  { id: "unit-eval-observability-03", topicId: "topic-eval-observability", order: 3, title: "Latency/cost/quality dashboard", description: "Build a monitoring view.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build a dashboard for latency/cost/quality.", completionCriteria: "Dashboard surfaces regressions.", skillIds: ["skill-observability"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-observability-02"] },

  // 12.4 Evaluation in CI
  { id: "unit-eval-ci-01", topicId: "topic-eval-ci", order: 1, title: "Eval-in-CI", description: "Gates, thresholds, drift.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "advanced", instructions: "Learn evaluation gates in CI.", completionCriteria: "You can describe an eval gate.", skillIds: ["skill-evaluation", "skill-git-cicd"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-eval-ci-02", topicId: "topic-eval-ci", order: 2, title: "CI eval gate for a repo", description: "Add a gate to CI.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Add an eval gate to a repo's CI.", completionCriteria: "CI runs the eval on each change.", skillIds: ["skill-llmops", "skill-git-cicd"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-ci-01"] },
  { id: "unit-eval-ci-03", topicId: "topic-eval-ci", order: 3, title: "Regress and confirm", description: "Verify the gate catches it.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Intentionally regress and confirm the gate fails.", completionCriteria: "The gate blocks the regression.", skillIds: ["skill-evaluation"], resourceIds: [], recommendedAfterUnitIds: ["unit-eval-ci-02"] },

  // 13.1 Threat Landscape
  { id: "unit-sec-threat-model-01", topicId: "topic-sec-threat-model", order: 1, title: "OWASP LLM Top 10", description: "Injection, leakage, agency, supply chain.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Learn the OWASP LLM Top 10.", completionCriteria: "You can enumerate LLM-specific risks.", skillIds: ["skill-ai-security"], resourceIds: ["resource-owasp-llm-top10"], recommendedAfterUnitIds: [] },
  { id: "unit-sec-threat-model-02", topicId: "topic-sec-threat-model", order: 2, title: "Threat-model your P3", description: "Apply to a real app.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Threat-model your RAG app.", completionCriteria: "You produce a risk list for the app.", skillIds: ["skill-ai-security"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-threat-model-01"] },

  // 13.2 Prompt Injection & Defenses
  { id: "unit-sec-prompt-injection-01", topicId: "topic-sec-prompt-injection", order: 1, title: "Injection & defenses", description: "Direct/indirect injection, mitigations.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn prompt injection and layered defenses.", completionCriteria: "You can describe indirect injection.", skillIds: ["skill-prompt-injection"], resourceIds: ["resource-prompt-injection-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-sec-prompt-injection-02", topicId: "topic-sec-prompt-injection", order: 2, title: "Attack your own app", description: "Demonstrate injection.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Attempt injection against your own RAG app.", completionCriteria: "You reproduce an injection.", skillIds: ["skill-prompt-injection"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-prompt-injection-01"] },
  { id: "unit-sec-prompt-injection-03", topicId: "topic-sec-prompt-injection", order: 3, title: "Add injection defenses", description: "Harden the RAG app.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Add layered injection defenses to RAG.", completionCriteria: "Untrusted docs can't hijack the app.", skillIds: ["skill-prompt-injection", "skill-ai-security"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-prompt-injection-02"] },
  { id: "unit-sec-prompt-injection-04", topicId: "topic-sec-prompt-injection", order: 4, title: "Re-run attacks", description: "Confirm mitigation.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Re-run injection attacks after hardening.", completionCriteria: "Attacks now fail.", skillIds: ["skill-prompt-injection"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-prompt-injection-03"] },

  // 13.3 Guardrails
  { id: "unit-sec-guardrails-01", topicId: "topic-sec-guardrails", order: 1, title: "Guardrails & moderation", description: "Validation, moderation, least privilege.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn guardrails and safe output handling.", completionCriteria: "You can list guardrail layers.", skillIds: ["skill-guardrails"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-sec-guardrails-02", topicId: "topic-sec-guardrails", order: 2, title: "Add output validation", description: "Validate model output.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Add output validation to an app.", completionCriteria: "Invalid outputs are rejected.", skillIds: ["skill-guardrails"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-guardrails-01"] },
  { id: "unit-sec-guardrails-03", topicId: "topic-sec-guardrails", order: 3, title: "Guardrail layer for your agent", description: "Safe tool execution.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Build a guardrail layer around your agent.", completionCriteria: "Agent can't take unsafe actions.", skillIds: ["skill-guardrails", "skill-ai-security"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-guardrails-02"] },
  { id: "unit-sec-guardrails-04", topicId: "topic-sec-guardrails", order: 4, title: "Red-team the guardrails", description: "Attempt to bypass.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Red-team your guardrails.", completionCriteria: "Guardrails withstand the attempts.", skillIds: ["skill-guardrails"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-guardrails-03"] },

  // 13.4 Data Privacy
  { id: "unit-sec-data-privacy-01", topicId: "topic-sec-data-privacy", order: 1, title: "Privacy & secrets", description: "Secrets, residency, PII logging.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn data privacy and secret handling.", completionCriteria: "You can outline a data-handling policy.", skillIds: ["skill-ai-security", "skill-env-tooling"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-sec-data-privacy-02", topicId: "topic-sec-data-privacy", order: 2, title: "Audit an app's data handling", description: "Review for leaks.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Audit an app's data handling.", completionCriteria: "You identify and fix leak risks.", skillIds: ["skill-ai-security"], resourceIds: [], recommendedAfterUnitIds: ["unit-sec-data-privacy-01"] },

  // 14.1 Serving AI as an API
  { id: "unit-prod-api-01", topicId: "topic-prod-api", order: 1, title: "FastAPI for AI", description: "Endpoints, async, streaming, validation.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn FastAPI for AI services.", completionCriteria: "You can design endpoints for an AI app.", skillIds: ["skill-fastapi"], resourceIds: ["resource-fastapi-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-prod-api-02", topicId: "topic-prod-api", order: 2, title: "Build endpoints", description: "Create validated endpoints.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build validated FastAPI endpoints.", completionCriteria: "Endpoints validate inputs/outputs.", skillIds: ["skill-fastapi"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-api-01"] },
  { id: "unit-prod-api-03", topicId: "topic-prod-api", order: 3, title: "Expose P3 as streaming API", description: "Wrap the RAG app.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Expose Project P3 as a streaming API.", completionCriteria: "API streams responses with error handling.", skillIds: ["skill-fastapi", "skill-resilience"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-api-02"] },
  { id: "unit-prod-api-04", topicId: "topic-prod-api", order: 4, title: "Load/error test", description: "Verify robustness.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Load and error test the API.", completionCriteria: "API stays stable under load/errors.", skillIds: ["skill-fastapi"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-api-03"] },

  // 14.2 Containerization with Docker
  { id: "unit-prod-docker-01", topicId: "topic-prod-docker", order: 1, title: "Docker essentials", description: "Dockerfile, images, compose.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn Docker for AI services.", completionCriteria: "You can write a basic Dockerfile.", skillIds: ["skill-docker"], resourceIds: ["resource-docker-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-prod-docker-02", topicId: "topic-prod-docker", order: 2, title: "Write a Dockerfile", description: "Containerize the API.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Write a Dockerfile for your API.", completionCriteria: "Image builds and runs.", skillIds: ["skill-docker"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-docker-01"] },
  { id: "unit-prod-docker-03", topicId: "topic-prod-docker", order: 3, title: "Containerize API + deps", description: "Compose with dependencies.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Containerize the API and dependencies with compose.", completionCriteria: "Compose brings up the full stack.", skillIds: ["skill-docker"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-docker-02"] },
  { id: "unit-prod-docker-04", topicId: "topic-prod-docker", order: 4, title: "Optimize image size/startup", description: "Slim the image.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Optimize image size and startup time.", completionCriteria: "Image is lean and starts fast.", skillIds: ["skill-docker"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-docker-03"] },

  // 14.3 Deploying to the Cloud
  { id: "unit-prod-cloud-deploy-01", topicId: "topic-prod-cloud-deploy", order: 1, title: "Cloud deployment", description: "Hosting, config, scaling, logs.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn container deployment to the cloud.", completionCriteria: "You can outline a deploy with health checks.", skillIds: ["skill-cloud-deployment"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-prod-cloud-deploy-02", topicId: "topic-prod-cloud-deploy", order: 2, title: "Deploy the container", description: "Publish to a managed service.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Deploy the container to a managed service.", completionCriteria: "API is reachable with logging.", skillIds: ["skill-cloud-deployment"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-cloud-deploy-01"] },
  { id: "unit-prod-cloud-deploy-03", topicId: "topic-prod-cloud-deploy", order: 3, title: "Verify scaling/logging", description: "Confirm operability.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Verify scaling and logging behavior.", completionCriteria: "Scaling and logs work as expected.", skillIds: ["skill-cloud-deployment"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-cloud-deploy-02"] },

  // 14.4 Azure AI Platform in Depth
  { id: "unit-prod-azure-ai-01", topicId: "topic-prod-azure-ai", order: 1, title: "Azure AI stack", description: "OpenAI, AI Search, Container Apps, Key Vault.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "advanced", instructions: "Learn the enterprise Azure AI stack.", completionCriteria: "You can describe managed identity + Key Vault.", skillIds: ["skill-azure-ai"], resourceIds: ["resource-azure-container-apps"], recommendedAfterUnitIds: [] },
  { id: "unit-prod-azure-ai-02", topicId: "topic-prod-azure-ai", order: 2, title: "Provision core resources", description: "Set up Azure resources.", mode: "practice", stage: "practicing", estimatedMinutes: 150, difficulty: "advanced", instructions: "Provision Azure OpenAI, AI Search and Key Vault.", completionCriteria: "Resources are provisioned securely.", skillIds: ["skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-azure-ai-01"] },
  { id: "unit-prod-azure-ai-03", topicId: "topic-prod-azure-ai", order: 3, title: "Deploy RAG on Azure", description: "End-to-end Azure RAG.", mode: "build", stage: "building", estimatedMinutes: 210, difficulty: "advanced", instructions: "Deploy a RAG app end-to-end on Azure.", completionCriteria: "RAG runs on Azure with managed identity.", skillIds: ["skill-azure-ai", "skill-cloud-deployment"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-azure-ai-02"] },
  { id: "unit-prod-azure-ai-04", topicId: "topic-prod-azure-ai", order: 4, title: "Security & cost review", description: "Audit the Azure app.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Review security and cost of the Azure app.", completionCriteria: "You address key security/cost findings.", skillIds: ["skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-azure-ai-03"] },

  // 14.5 CI/CD, Monitoring & LLMOps (P6 anchor)
  { id: "unit-prod-cicd-ops-01", topicId: "topic-prod-cicd-ops", order: 1, title: "LLMOps & CI/CD", description: "Pipelines, monitoring, rollback.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "advanced", instructions: "Learn LLMOps and CI/CD for AI apps.", completionCriteria: "You can outline a deploy pipeline.", skillIds: ["skill-llmops", "skill-git-cicd"], resourceIds: ["resource-cicd-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-prod-cicd-ops-02", topicId: "topic-prod-cicd-ops", order: 2, title: "Pipeline w/ eval gate + monitoring", description: "Automate deploy for P6.", mode: "build", stage: "building", estimatedMinutes: 210, difficulty: "advanced", instructions: "Build a pipeline with eval gate and monitoring for Project P6.", completionCriteria: "Pipeline tests, evals, deploys and monitors.", skillIds: ["skill-llmops", "skill-observability"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-cicd-ops-01"] },
  { id: "unit-prod-cicd-ops-03", topicId: "topic-prod-cicd-ops", order: 3, title: "Simulate incident & roll back", description: "Practice rollback.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Simulate an incident and roll back.", completionCriteria: "Rollback restores a healthy state.", skillIds: ["skill-llmops"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-cicd-ops-02"] },
  { id: "unit-prod-cicd-ops-04", topicId: "topic-prod-cicd-ops", order: 4, title: "Deliver Project P6", description: "Finalize the production service.", mode: "project", stage: "building", estimatedMinutes: 210, difficulty: "advanced", instructions: "Combine production skills into Project P6.", completionCriteria: "P6 is deployed, monitored, secured and cost-optimized.", skillIds: ["skill-llmops", "skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-cicd-ops-03"] },

  // 14.6 Scaling, Caching & Cost Optimization
  { id: "unit-prod-scaling-cost-01", topicId: "topic-prod-scaling-cost", order: 1, title: "Scaling & cost patterns", description: "Caching, batching, routing, fallback.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "advanced", instructions: "Learn scaling and cost-optimization patterns.", completionCriteria: "You can pick a caching strategy.", skillIds: ["skill-cost-optimization"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-prod-scaling-cost-02", topicId: "topic-prod-scaling-cost", order: 2, title: "Add caching + model routing", description: "Implement optimizations.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "advanced", instructions: "Add caching and model routing to an app.", completionCriteria: "Cost/latency drop without quality loss.", skillIds: ["skill-cost-optimization", "skill-resilience"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-scaling-cost-01"] },
  { id: "unit-prod-scaling-cost-03", topicId: "topic-prod-scaling-cost", order: 3, title: "Measure cost/latency deltas", description: "Quantify the gains.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "advanced", instructions: "Measure cost and latency improvements.", completionCriteria: "You quantify the improvement.", skillIds: ["skill-cost-optimization"], resourceIds: [], recommendedAfterUnitIds: ["unit-prod-scaling-cost-02"] },

  // 15.1 Context Engineering
  { id: "unit-adv-context-engineering-01", topicId: "topic-adv-context-engineering", order: 1, title: "Context engineering", description: "Assembly, caching, long-context tradeoffs.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn context-engineering patterns.", completionCriteria: "You can compare long-context vs RAG.", skillIds: ["skill-context-engineering"], resourceIds: ["resource-context-engineering"], recommendedAfterUnitIds: [] },
  { id: "unit-adv-context-engineering-02", topicId: "topic-adv-context-engineering", order: 2, title: "Context-optimized pipeline", description: "Build an optimized pipeline.", mode: "build", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Build a context-optimized pipeline.", completionCriteria: "Pipeline uses context deliberately.", skillIds: ["skill-context-engineering", "skill-rag"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-context-engineering-01"] },
  { id: "unit-adv-context-engineering-03", topicId: "topic-adv-context-engineering", order: 3, title: "Compare vs naive RAG", description: "Measure the gain.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Compare the pipeline to naive RAG.", completionCriteria: "You show a measurable improvement.", skillIds: ["skill-context-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-context-engineering-02"] },

  // 15.2 Reasoning Models (optional-depth)
  { id: "unit-adv-reasoning-models-01", topicId: "topic-adv-reasoning-models", order: 1, title: "Reasoning models", description: "Test-time compute, prompting.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn reasoning models and their tradeoffs.", completionCriteria: "You can describe when they help.", skillIds: ["skill-ml-literacy"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-adv-reasoning-models-02", topicId: "topic-adv-reasoning-models", order: 2, title: "Compare on hard tasks", description: "Benchmark on tough problems.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Compare reasoning models on hard tasks.", completionCriteria: "You measure the quality difference.", skillIds: ["skill-ml-literacy"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-reasoning-models-01"] },
  { id: "unit-adv-reasoning-models-03", topicId: "topic-adv-reasoning-models", order: 3, title: "Cost/quality analysis", description: "Judge the tradeoff.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Analyze cost vs quality for reasoning models.", completionCriteria: "You decide when they're worth it.", skillIds: ["skill-ml-literacy"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-reasoning-models-02"] },

  // 15.3 ML Literacy (optional-depth)
  { id: "unit-adv-ml-literacy-01", topicId: "topic-adv-ml-literacy", order: 1, title: "ML concepts for literacy", description: "Training, overfitting, embeddings origins.", mode: "learn", stage: "learning", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Learn just-enough ML concepts.", completionCriteria: "You can explain the key ideas.", skillIds: ["skill-ml-literacy"], resourceIds: ["resource-ml-literacy"], recommendedAfterUnitIds: [] },
  { id: "unit-adv-ml-literacy-02", topicId: "topic-adv-ml-literacy", order: 2, title: "Explain-back key ideas", description: "Reinforce understanding.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Explain the ML concepts back.", completionCriteria: "You can teach the ideas without math.", skillIds: ["skill-ml-literacy"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-ml-literacy-01"] },

  // 15.4 Emerging Patterns (optional-depth)
  { id: "unit-adv-emerging-01", topicId: "topic-adv-emerging", order: 1, title: "How to stay current", description: "Reading, changelogs, protocols.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "advanced", instructions: "Learn to track the field responsibly.", completionCriteria: "You have a current-awareness method.", skillIds: ["skill-continuous-learning"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-adv-emerging-02", topicId: "topic-adv-emerging", order: 2, title: "Maintain a 'what changed' log", description: "Start a durable habit.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "advanced", instructions: "Maintain a personal 'what changed' log.", completionCriteria: "You keep an updated learning log.", skillIds: ["skill-continuous-learning"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-emerging-01"] },

  // 15.5 Specialization Capstone (P7 anchor)
  { id: "unit-adv-specialization-capstone-01", topicId: "topic-adv-specialization-capstone", order: 1, title: "Build a niche system", description: "Self-directed advanced project.", mode: "build", stage: "building", estimatedMinutes: 240, difficulty: "advanced", instructions: "Build a niche advanced system in a chosen area.", completionCriteria: "A working niche system is built.", skillIds: ["skill-continuous-learning"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-adv-specialization-capstone-02", topicId: "topic-adv-specialization-capstone", order: 2, title: "Write-up & portfolio polish", description: "Document and polish.", mode: "review", stage: "reviewing", estimatedMinutes: 120, difficulty: "advanced", instructions: "Write up the project and polish the portfolio.", completionCriteria: "A strong write-up accompanies the project.", skillIds: ["skill-continuous-learning"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-specialization-capstone-01"] },
  { id: "unit-adv-specialization-capstone-03", topicId: "topic-adv-specialization-capstone", order: 3, title: "Deliver Project P7", description: "Finalize the specialization capstone.", mode: "project", stage: "building", estimatedMinutes: 180, difficulty: "advanced", instructions: "Finalize Project P7 as a portfolio-grade capstone.", completionCriteria: "P7 is shipped with documentation.", skillIds: ["skill-continuous-learning"], resourceIds: [], recommendedAfterUnitIds: ["unit-adv-specialization-capstone-02"] },
];
