import type { LearningUnit } from "./types";

// Learning units for categories 1–4. Mode and Stage are SEPARATE fields.
// stage mapping: learn→learning, practice→practicing, build→building,
// review→reviewing, project→building. recommendedAfterUnitIds is advisory only.
export const unitsPartA: LearningUnit[] = [
  // 1.1 Python Essentials
  { id: "unit-py-core-syntax-01", topicId: "topic-py-core-syntax", order: 1, title: "Core syntax tour", description: "Types, control flow, functions and comprehensions.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Work through the core Python syntax with runnable examples.", completionCriteria: "You can read and explain basic Python syntax.", skillIds: ["skill-python"], resourceIds: ["resource-python-official-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-py-core-syntax-02", topicId: "topic-py-core-syntax", order: 2, title: "10 micro-exercises", description: "Parse/transform lists and dicts.", mode: "practice", stage: "practicing", estimatedMinutes: 150, difficulty: "beginner", instructions: "Solve ten short exercises manipulating lists and dicts.", completionCriteria: "All ten exercises produce correct output.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-core-syntax-01"] },
  { id: "unit-py-core-syntax-03", topicId: "topic-py-core-syntax", order: 3, title: "Gotchas retrieval quiz", description: "Recall common Python gotchas.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Answer a short quiz on mutable defaults and is vs ==.", completionCriteria: "You correctly identify each gotcha.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-core-syntax-02"] },

  // 1.2 Data Handling & JSON
  { id: "unit-py-data-structures-01", topicId: "topic-py-data-structures", order: 1, title: "JSON & nested data", description: "The json module and nested access patterns.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "beginner", instructions: "Learn to load, navigate and serialize JSON.", completionCriteria: "You can access nested JSON fields safely.", skillIds: ["skill-data-handling"], resourceIds: ["resource-json-handling-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-py-data-structures-02", topicId: "topic-py-data-structures", order: 2, title: "Transform API payloads", description: "Reshape sample API-shaped payloads.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Transform provided nested payloads into flat records.", completionCriteria: "Output matches the expected shape.", skillIds: ["skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-data-structures-01"] },
  { id: "unit-py-data-structures-03", topicId: "topic-py-data-structures", order: 3, title: "Normalize a nested JSON file", description: "Flatten/normalize a nested JSON document.", mode: "build", stage: "building", estimatedMinutes: 90, difficulty: "beginner", instructions: "Write a script that flattens a nested JSON file.", completionCriteria: "Script outputs a clean normalized structure.", skillIds: ["skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-data-structures-02"] },
  { id: "unit-py-data-structures-04", topicId: "topic-py-data-structures", order: 4, title: "Debug a broken parser", description: "Find and fix parsing bugs.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Diagnose a failing parser and correct it.", completionCriteria: "Parser handles the tricky inputs correctly.", skillIds: ["skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-data-structures-03"] },

  // 1.3 Functions, Modules & Project Layout
  { id: "unit-py-functions-modules-01", topicId: "topic-py-functions-modules", order: 1, title: "Modules & type hints", description: "Modules, imports, __main__ and type hints.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "beginner", instructions: "Learn module structure and typed function signatures.", completionCriteria: "You can explain imports and type hints.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-py-functions-modules-02", topicId: "topic-py-functions-modules", order: 2, title: "Refactor a script into modules", description: "Split a single script into modules.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Refactor a monolithic script into logical modules.", completionCriteria: "Code runs and is organized into modules.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-functions-modules-01"] },
  { id: "unit-py-functions-modules-03", topicId: "topic-py-functions-modules", order: 3, title: "Reusable utility package", description: "Build a small reusable package.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "beginner", instructions: "Create a small importable utility package.", completionCriteria: "Package imports and functions work from another module.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-functions-modules-02"] },

  // 1.4 Environments, Packages, Secrets & Git/CI
  { id: "unit-py-env-tooling-01", topicId: "topic-py-env-tooling", order: 1, title: "Envs & secrets hygiene", description: "venv, pip, dotenv and safe key handling.", mode: "learn", stage: "learning", estimatedMinutes: 75, difficulty: "beginner", instructions: "Learn isolated environments and secret hygiene.", completionCriteria: "You can explain why keys never go in code.", skillIds: ["skill-env-tooling"], resourceIds: ["resource-venv-dotenv-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-py-env-tooling-02", topicId: "topic-py-env-tooling", order: 2, title: "Set up venv + dotenv", description: "Create an env and load a secret.", mode: "practice", stage: "practicing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Create a venv, install a package and load a secret from .env.", completionCriteria: "Secret loads from env vars, not code.", skillIds: ["skill-env-tooling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-env-tooling-01"] },
  { id: "unit-py-env-tooling-03", topicId: "topic-py-env-tooling", order: 3, title: "Starter template repo", description: "A reproducible project starter.", mode: "build", stage: "building", estimatedMinutes: 90, difficulty: "beginner", instructions: "Build a starter template with env config and requirements.", completionCriteria: "Template reproduces the environment cleanly.", skillIds: ["skill-env-tooling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-env-tooling-02"] },
  { id: "unit-py-env-tooling-04", topicId: "topic-py-env-tooling", order: 4, title: "Git workflow & CI basics", description: "Branches, commits, PRs, GitHub Actions, CI vs CD.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "beginner", instructions: "Learn the Git workflow and basic pipeline concepts.", completionCriteria: "You can explain branches, PRs and CI vs CD.", skillIds: ["skill-git-cicd"], resourceIds: ["resource-git-actions-basics"], recommendedAfterUnitIds: ["unit-py-env-tooling-01"] },
  { id: "unit-py-env-tooling-05", topicId: "topic-py-env-tooling", order: 5, title: "Branch → PR → Actions", description: "Open a PR that triggers CI.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "beginner", instructions: "Init a repo, branch, commit, open a PR and add a GitHub Actions workflow that runs on push.", completionCriteria: "A PR triggers a passing GitHub Actions run.", skillIds: ["skill-git-cicd"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-env-tooling-04"] },

  // 1.5 HTTP, Async & API Calls
  { id: "unit-py-async-http-01", topicId: "topic-py-async-http", order: 1, title: "HTTP + async basics", description: "REST, headers/auth and async/await.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Learn HTTP verbs, auth and basic async.", completionCriteria: "You can describe an async request flow.", skillIds: ["skill-http-async"], resourceIds: ["resource-httpx-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-py-async-http-02", topicId: "topic-py-async-http", order: 2, title: "Call a public REST API", description: "Fetch and parse JSON from a REST API.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Call a public API and parse its JSON response.", completionCriteria: "You parse and print selected fields.", skillIds: ["skill-http-async"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-async-http-01"] },
  { id: "unit-py-async-http-03", topicId: "topic-py-async-http", order: 3, title: "Resilient API client", description: "Add retries and timeouts.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "beginner", instructions: "Build a client with retry/timeout handling.", completionCriteria: "Client recovers from transient failures.", skillIds: ["skill-http-async"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-async-http-02"] },
  { id: "unit-py-async-http-04", topicId: "topic-py-async-http", order: 4, title: "Sync vs async timing", description: "Compare sync and async throughput.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Measure timing of sync vs async calls.", completionCriteria: "You explain when async helps.", skillIds: ["skill-http-async"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-async-http-03"] },

  // 1.6 Errors, Logging & Debugging
  { id: "unit-py-errors-logging-01", topicId: "topic-py-errors-logging", order: 1, title: "Errors & logging", description: "Exceptions, custom errors and logging.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "beginner", instructions: "Learn exception patterns and structured logging.", completionCriteria: "You can read a traceback and add logging.", skillIds: ["skill-observability-basics"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-py-errors-logging-02", topicId: "topic-py-errors-logging", order: 2, title: "Add handling to a client", description: "Harden the earlier API client.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Add error handling and logging to your API client.", completionCriteria: "Failures are logged and handled gracefully.", skillIds: ["skill-observability-basics"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-errors-logging-01"] },
  { id: "unit-py-errors-logging-03", topicId: "topic-py-errors-logging", order: 3, title: "Diagnose tracebacks", description: "Interpret given tracebacks.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Diagnose the root cause of several tracebacks.", completionCriteria: "You correctly identify each root cause.", skillIds: ["skill-observability-basics"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-errors-logging-02"] },

  // 1.7 Practical Data Tooling
  { id: "unit-py-data-libs-01", topicId: "topic-py-data-libs", order: 1, title: "pandas/numpy essentials", description: "DataFrames, Series and arrays.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Learn to load and inspect data with pandas/numpy.", completionCriteria: "You can load a CSV/JSON into a DataFrame.", skillIds: ["skill-data-handling"], resourceIds: ["resource-pandas-intro"], recommendedAfterUnitIds: [] },
  { id: "unit-py-data-libs-02", topicId: "topic-py-data-libs", order: 2, title: "Clean a small dataset", description: "Filter and select rows/columns.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Clean a provided messy dataset.", completionCriteria: "Cleaned dataset has consistent, usable rows.", skillIds: ["skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-data-libs-01"] },
  { id: "unit-py-data-libs-03", topicId: "topic-py-data-libs", order: 3, title: "Prep a text corpus", description: "Load → clean → export text for embedding.", mode: "build", stage: "building", estimatedMinutes: 90, difficulty: "beginner", instructions: "Build a small load→clean→export pipeline for text.", completionCriteria: "Corpus is exported ready for embedding.", skillIds: ["skill-data-handling"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-data-libs-02"] },

  // 1.8 Optional General Python & CS Depth
  { id: "unit-py-optional-depth-01", topicId: "topic-py-optional-depth", order: 1, title: "Curated deep-dive links", description: "OOP, decorators, generators, testing, packaging.", mode: "learn", stage: "learning", estimatedMinutes: 180, difficulty: "intermediate", instructions: "Explore deeper Python topics as needed.", completionCriteria: "You have a reference map of deeper topics.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-py-optional-depth-02", topicId: "topic-py-optional-depth", order: 2, title: "Do I need this yet?", description: "Self-check on relevance.", mode: "review", stage: "reviewing", estimatedMinutes: 30, difficulty: "intermediate", instructions: "Assess whether deeper Python is currently needed.", completionCriteria: "You make a deliberate learn/defer decision.", skillIds: ["skill-python"], resourceIds: [], recommendedAfterUnitIds: ["unit-py-optional-depth-01"] },

  // 2.1 What LLMs Are
  { id: "unit-llm-what-are-01", topicId: "topic-llm-what-are", order: 1, title: "Conceptual model of LLMs", description: "Next-token prediction, pretraining vs inference.", mode: "learn", stage: "learning", estimatedMinutes: 150, difficulty: "beginner", instructions: "Build a conceptual model of how LLMs work.", completionCriteria: "You can explain next-token prediction.", skillIds: ["skill-llm-fundamentals"], resourceIds: ["resource-llm-conceptual-overview"], recommendedAfterUnitIds: [] },
  { id: "unit-llm-what-are-02", topicId: "topic-llm-what-are", order: 2, title: "Explain-back / flashcards", description: "Explain why LLMs hallucinate.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Explain the concepts back in your own words.", completionCriteria: "You can teach the ideas to a peer.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-what-are-01"] },

  // 2.2 Tokens, Context Windows & Limits
  { id: "unit-llm-tokens-context-01", topicId: "topic-llm-tokens-context", order: 1, title: "Tokenization & context", description: "Tokens, windows, cost.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Learn tokenization and context limits.", completionCriteria: "You can explain tokens vs words.", skillIds: ["skill-tokenization"], resourceIds: ["resource-tokenizer-tool"], recommendedAfterUnitIds: [] },
  { id: "unit-llm-tokens-context-02", topicId: "topic-llm-tokens-context", order: 2, title: "Count tokens", description: "Use a tokenizer on sample texts.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Count tokens for several sample texts.", completionCriteria: "You produce accurate token counts.", skillIds: ["skill-tokenization"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-tokens-context-01"] },
  { id: "unit-llm-tokens-context-03", topicId: "topic-llm-tokens-context", order: 3, title: "Predict overflows", description: "Which prompts overflow a window?", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Predict which prompts exceed a context window.", completionCriteria: "Your predictions match measured counts.", skillIds: ["skill-tokenization"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-tokens-context-02"] },

  // 2.3 Capabilities, Hallucination & Failure Modes
  { id: "unit-llm-capabilities-limits-01", topicId: "topic-llm-capabilities-limits", order: 1, title: "Failure modes", description: "Hallucination, non-determinism, cutoff.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Learn common LLM failure modes.", completionCriteria: "You can list and explain failure modes.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-llm-capabilities-limits-02", topicId: "topic-llm-capabilities-limits", order: 2, title: "Provoke failures", description: "Document three failure cases.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Deliberately trigger and record three failures.", completionCriteria: "Three documented, reproducible failures.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-capabilities-limits-01"] },
  { id: "unit-llm-capabilities-limits-03", topicId: "topic-llm-capabilities-limits", order: 3, title: "Categorize failures", description: "Group failures by type.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Categorize the failures you produced.", completionCriteria: "Each failure is correctly categorized.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-capabilities-limits-02"] },

  // 2.4 Model Landscape & Selection
  { id: "unit-llm-landscape-01", topicId: "topic-llm-landscape", order: 1, title: "Landscape overview", description: "Proprietary vs open families.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Survey the model landscape and licensing.", completionCriteria: "You can name major families and tradeoffs.", skillIds: ["skill-model-selection"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-llm-landscape-02", topicId: "topic-llm-landscape", order: 2, title: "Comparison table", description: "Build a selection comparison table.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Create a model comparison table on cost/quality/latency.", completionCriteria: "Table supports a defensible choice.", skillIds: ["skill-model-selection"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-landscape-01"] },
  { id: "unit-llm-landscape-03", topicId: "topic-llm-landscape", order: 3, title: "Defend three choices", description: "Justify picks for three scenarios.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Choose and justify a model for three scenarios.", completionCriteria: "Each choice is justified on real constraints.", skillIds: ["skill-model-selection"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-landscape-02"] },

  // 2.5 Inference Parameters
  { id: "unit-llm-inference-params-01", topicId: "topic-llm-inference-params", order: 1, title: "Params explained", description: "Temperature, top-p, max tokens, stop.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "beginner", instructions: "Learn what each sampling parameter does.", completionCriteria: "You can explain each parameter's effect.", skillIds: ["skill-llm-fundamentals"], resourceIds: ["resource-inference-params-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-llm-inference-params-02", topicId: "topic-llm-inference-params", order: 2, title: "Sweep params", description: "Observe effects on one prompt.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "beginner", instructions: "Vary params on a single prompt and observe outputs.", completionCriteria: "You document the effect of each param.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-inference-params-01"] },
  { id: "unit-llm-inference-params-03", topicId: "topic-llm-inference-params", order: 3, title: "Map params → use-cases", description: "Match settings to tasks.", mode: "review", stage: "reviewing", estimatedMinutes: 45, difficulty: "beginner", instructions: "Map parameter settings to appropriate use cases.", completionCriteria: "Your mapping is sensible and justified.", skillIds: ["skill-llm-fundamentals"], resourceIds: [], recommendedAfterUnitIds: ["unit-llm-inference-params-02"] },

  // 3.1 First LLM API Call
  { id: "unit-api-first-call-01", topicId: "topic-api-first-call", order: 1, title: "Chat API + Azure setup", description: "Roles, usage and Azure deployment names.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "beginner", instructions: "Learn the chat API and Azure OpenAI setup.", completionCriteria: "You can describe roles and usage fields.", skillIds: ["skill-llm-apis", "skill-azure-ai"], resourceIds: ["resource-chat-api-docs", "resource-azure-openai-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-api-first-call-02", topicId: "topic-api-first-call", order: 2, title: "Send varied prompts", description: "Experiment with message roles.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "beginner", instructions: "Send several prompts and inspect responses/usage.", completionCriteria: "You read the response and usage correctly.", skillIds: ["skill-llm-apis"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-first-call-01"] },
  { id: "unit-api-first-call-03", topicId: "topic-api-first-call", order: 3, title: "Q&A CLI (provider-configurable)", description: "A CLI answering via the API.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "beginner", instructions: "Build a CLI that answers questions, provider set via env.", completionCriteria: "CLI works against OpenAI and Azure OpenAI.", skillIds: ["skill-llm-apis", "skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-first-call-02"] },
  { id: "unit-api-first-call-04", topicId: "topic-api-first-call", order: 4, title: "Compare OpenAI vs Azure", description: "Contrast responses across providers.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "beginner", instructions: "Compare outputs from OpenAI and Azure OpenAI.", completionCriteria: "You note meaningful differences and parity.", skillIds: ["skill-azure-ai"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-first-call-03"] },

  // 3.2 Prompt Engineering Foundations
  { id: "unit-api-prompting-core-01", topicId: "topic-api-prompting-core", order: 1, title: "Prompting principles", description: "System prompts, few-shot, delimiters.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn core prompting principles.", completionCriteria: "You can structure a reliable prompt.", skillIds: ["skill-prompt-engineering"], resourceIds: ["resource-prompting-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-api-prompting-core-02", topicId: "topic-api-prompting-core", order: 2, title: "Improve 5 weak prompts", description: "Systematically fix flaky prompts.", mode: "practice", stage: "practicing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Rewrite five weak prompts for consistency.", completionCriteria: "Each rewritten prompt is more reliable.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-prompting-core-01"] },
  { id: "unit-api-prompting-core-03", topicId: "topic-api-prompting-core", order: 3, title: "Reusable prompt library", description: "Build a template library.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build a small reusable prompt-template library.", completionCriteria: "Templates are parameterized and reusable.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-prompting-core-02"] },
  { id: "unit-api-prompting-core-04", topicId: "topic-api-prompting-core", order: 4, title: "A/B compare variants", description: "Measure prompt variants.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "A/B test prompt variants on a task.", completionCriteria: "You pick the better variant with evidence.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-prompting-core-03"] },

  // 3.3 Reasoning & Prompt Patterns
  { id: "unit-api-reasoning-patterns-01", topicId: "topic-api-reasoning-patterns", order: 1, title: "Reasoning patterns", description: "CoT, decomposition, self-critique.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn reasoning prompt patterns and their costs.", completionCriteria: "You can name when each pattern helps.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-api-reasoning-patterns-02", topicId: "topic-api-reasoning-patterns", order: 2, title: "Apply to a multi-step task", description: "Use a pattern on a hard task.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Apply a reasoning pattern to a multi-step task.", completionCriteria: "Accuracy improves on the task.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-reasoning-patterns-01"] },
  { id: "unit-api-reasoning-patterns-03", topicId: "topic-api-reasoning-patterns", order: 3, title: "Accuracy vs cost", description: "Measure the tradeoff.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Measure accuracy gains against token cost.", completionCriteria: "You choose the minimal effective pattern.", skillIds: ["skill-prompt-engineering"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-reasoning-patterns-02"] },

  // 3.4 Structured Output & Function/Tool Calling Basics
  { id: "unit-api-structured-output-01", topicId: "topic-api-structured-output", order: 1, title: "Structured outputs & function calling", description: "JSON mode, schemas, tool calling.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn structured outputs and basic function calling.", completionCriteria: "You can define a schema for an output.", skillIds: ["skill-structured-outputs"], resourceIds: ["resource-structured-outputs-docs", "resource-pydantic-docs"], recommendedAfterUnitIds: [] },
  { id: "unit-api-structured-output-02", topicId: "topic-api-structured-output", order: 2, title: "Schema for an invoice extractor", description: "Extract fields into a schema.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Design a schema for invoice extraction.", completionCriteria: "Model output validates against the schema.", skillIds: ["skill-structured-outputs"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-structured-output-01"] },
  { id: "unit-api-structured-output-03", topicId: "topic-api-structured-output", order: 3, title: "Pydantic-validated extractor", description: "Return validated objects.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build an extractor returning validated pydantic objects.", completionCriteria: "Every output is a valid pydantic model.", skillIds: ["skill-structured-outputs"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-structured-output-02"] },
  { id: "unit-api-structured-output-04", topicId: "topic-api-structured-output", order: 4, title: "Fuzz with tricky inputs", description: "Test adversarial inputs.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Fuzz the extractor with malformed inputs.", completionCriteria: "Extractor stays schema-valid or fails safely.", skillIds: ["skill-structured-outputs"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-structured-output-03"] },

  // 3.5 Streaming, Errors, Retries & Cost Control
  { id: "unit-api-streaming-robustness-01", topicId: "topic-api-streaming-robustness", order: 1, title: "Streaming & resilience", description: "Streaming, rate limits, backoff, caching.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn streaming and resilience patterns.", completionCriteria: "You can describe backoff and caching.", skillIds: ["skill-resilience"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-api-streaming-robustness-02", topicId: "topic-api-streaming-robustness", order: 2, title: "Add retries/backoff", description: "Handle rate limits.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Add exponential backoff to API calls.", completionCriteria: "Calls recover from simulated 429s.", skillIds: ["skill-resilience"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-streaming-robustness-01"] },
  { id: "unit-api-streaming-robustness-03", topicId: "topic-api-streaming-robustness", order: 3, title: "Robust client + cost tracking", description: "Streaming, resilience and cost logging.", mode: "build", stage: "building", estimatedMinutes: 150, difficulty: "intermediate", instructions: "Build a robust LLM client wrapper with cost tracking.", completionCriteria: "Wrapper streams, retries and logs cost.", skillIds: ["skill-resilience", "skill-llm-apis"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-streaming-robustness-02"] },
  { id: "unit-api-streaming-robustness-04", topicId: "topic-api-streaming-robustness", order: 4, title: "Simulate rate limits", description: "Verify recovery under failure.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Simulate rate limits and confirm recovery.", completionCriteria: "Wrapper survives injected failures.", skillIds: ["skill-resilience"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-streaming-robustness-03"] },

  // 3.6 Conversation State & Memory Basics
  { id: "unit-api-conversation-state-01", topicId: "topic-api-conversation-state", order: 1, title: "Conversation state", description: "History, truncation, rolling summary.", mode: "learn", stage: "learning", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Learn multi-turn state and summarization.", completionCriteria: "You can describe a rolling-summary strategy.", skillIds: ["skill-tokenization", "skill-llm-apis"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-api-conversation-state-02", topicId: "topic-api-conversation-state", order: 2, title: "Implement history truncation", description: "Keep context within limits.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Implement history truncation for a chat loop.", completionCriteria: "Context stays within the window.", skillIds: ["skill-tokenization"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-conversation-state-01"] },
  { id: "unit-api-conversation-state-03", topicId: "topic-api-conversation-state", order: 3, title: "Multi-turn chat w/ summarization", description: "Coherent chat past the window.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build a multi-turn chat with rolling summarization.", completionCriteria: "Chat stays coherent past the context window.", skillIds: ["skill-llm-apis"], resourceIds: [], recommendedAfterUnitIds: ["unit-api-conversation-state-02"] },

  // 4.1 What Embeddings Represent
  { id: "unit-emb-concepts-01", topicId: "topic-emb-concepts", order: 1, title: "Embedding intuition & metrics", description: "Vector space and distance metrics.", mode: "learn", stage: "learning", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Learn embedding space and distance metrics.", completionCriteria: "You can choose a distance metric.", skillIds: ["skill-embeddings"], resourceIds: ["resource-embeddings-guide"], recommendedAfterUnitIds: [] },
  { id: "unit-emb-concepts-02", topicId: "topic-emb-concepts", order: 2, title: "Predict similarity rankings", description: "Rank pairs by hand.", mode: "review", stage: "reviewing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Predict similarity rankings for sentence pairs.", completionCriteria: "Predictions align with computed similarity.", skillIds: ["skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-concepts-01"] },

  // 4.2 Generating Embeddings
  { id: "unit-emb-generate-01", topicId: "topic-emb-generate", order: 1, title: "Embedding models", description: "API and local models, batching.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn how to generate embeddings efficiently.", completionCriteria: "You can describe batching and normalization.", skillIds: ["skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-emb-generate-02", topicId: "topic-emb-generate", order: 2, title: "Embed sample sentences", description: "Generate embeddings (API + local).", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Embed sample sentences via API and locally.", completionCriteria: "You produce vectors of correct dimension.", skillIds: ["skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-generate-01"] },
  { id: "unit-emb-generate-03", topicId: "topic-emb-generate", order: 3, title: "Batch-embed a document set", description: "Embed a corpus to disk.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Batch-embed a document set and store vectors.", completionCriteria: "Vectors persist and can be reloaded.", skillIds: ["skill-embeddings"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-generate-02"] },

  // 4.3 Similarity & Semantic Comparison
  { id: "unit-emb-similarity-01", topicId: "topic-emb-similarity", order: 1, title: "Similarity math (applied)", description: "Cosine, top-k, thresholds.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn applied similarity and ranking.", completionCriteria: "You can compute top-k by similarity.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-emb-similarity-02", topicId: "topic-emb-similarity", order: 2, title: "Compare sentence pairs", description: "Score similarity between sentences.", mode: "practice", stage: "practicing", estimatedMinutes: 75, difficulty: "intermediate", instructions: "Compute similarity for sentence pairs.", completionCriteria: "Scores match intuition.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-similarity-01"] },
  { id: "unit-emb-similarity-03", topicId: "topic-emb-similarity", order: 3, title: "In-memory semantic search", description: "Search over embeddings.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build an in-memory top-k semantic search.", completionCriteria: "Query returns most relevant items.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-similarity-02"] },
  { id: "unit-emb-similarity-04", topicId: "topic-emb-similarity", order: 4, title: "Why results rank higher", description: "Analyze rankings.", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Analyze why certain results rank higher.", completionCriteria: "You explain the ranking behavior.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-similarity-03"] },

  // 4.4 Chunking & Text Preparation
  { id: "unit-emb-chunking-01", topicId: "topic-emb-chunking", order: 1, title: "Chunking strategies", description: "Fixed/recursive/semantic, overlap.", mode: "learn", stage: "learning", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Learn chunking strategies and tradeoffs.", completionCriteria: "You can pick a chunking approach.", skillIds: ["skill-chunking"], resourceIds: ["resource-chunking-strategies"], recommendedAfterUnitIds: [] },
  { id: "unit-emb-chunking-02", topicId: "topic-emb-chunking", order: 2, title: "Chunk a document 3 ways", description: "Compare chunking approaches.", mode: "practice", stage: "practicing", estimatedMinutes: 90, difficulty: "intermediate", instructions: "Chunk one document three different ways.", completionCriteria: "You produce three labeled chunk sets.", skillIds: ["skill-chunking"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-chunking-01"] },
  { id: "unit-emb-chunking-03", topicId: "topic-emb-chunking", order: 3, title: "Configurable chunking pipeline", description: "Chunk + attach metadata.", mode: "build", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Build a configurable chunking pipeline with metadata.", completionCriteria: "Pipeline outputs chunks with metadata.", skillIds: ["skill-chunking"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-chunking-02"] },
  { id: "unit-emb-chunking-04", topicId: "topic-emb-chunking", order: 4, title: "Compare retrieval quality", description: "Which chunking retrieves best?", mode: "review", stage: "reviewing", estimatedMinutes: 60, difficulty: "intermediate", instructions: "Compare retrieval quality across chunking strategies.", completionCriteria: "You identify the best strategy with evidence.", skillIds: ["skill-chunking"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-chunking-03"] },

  // 4.5 Semantic Search System (produces semantic-search-core → P2)
  { id: "unit-emb-semantic-search-project-01", topicId: "topic-emb-semantic-search-project", order: 1, title: "Build semantic search core", description: "Ingest→chunk→embed→search over your docs.", mode: "build", stage: "building", estimatedMinutes: 240, difficulty: "intermediate", instructions: "Build an end-to-end semantic search over a personal doc set. This produces the 'semantic-search-core' artifact evolved by Project P2.", completionCriteria: "A working search tool returns relevant results over your docs.", skillIds: ["skill-semantic-search", "skill-embeddings", "skill-chunking"], resourceIds: [], recommendedAfterUnitIds: [] },
  { id: "unit-emb-semantic-search-project-02", topicId: "topic-emb-semantic-search-project", order: 2, title: "Tune for better results", description: "Improve chunking/metric.", mode: "review", stage: "reviewing", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Tune chunking and distance metric for quality.", completionCriteria: "Result quality measurably improves.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-semantic-search-project-01"] },
  { id: "unit-emb-semantic-search-project-03", topicId: "topic-emb-semantic-search-project", order: 3, title: "Hand off to Project P2", description: "Package the core for P2 to evolve.", mode: "project", stage: "building", estimatedMinutes: 120, difficulty: "intermediate", instructions: "Package the semantic-search-core so Project P2 can add infra, filtering, hybrid search and docs — no rebuild.", completionCriteria: "The core is documented and ready for P2 to extend.", skillIds: ["skill-semantic-search"], resourceIds: [], recommendedAfterUnitIds: ["unit-emb-semantic-search-project-02"] },
];
